// SPDX-FileCopyrightText: 2025 Gansu <68031780+GansuLalan@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 aa5g21 <aa5g21@soton.ac.uk>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using Content.Client.Materials;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Silo.UI;

[GenerateTypedNameReferences]
public sealed partial class SiloRelayMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly MaterialStorageSystem _materialStorage;

    public EntityUid Entity;

    public SiloRelayMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _materialStorage = _entityManager.System<MaterialStorageSystem>();
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;

        MaterialsList.SetOwner(Entity);
    }
}
