// SPDX-FileCopyrightText: 2025 ATDoop <bug@bug.bug>
// SPDX-FileCopyrightText: 2025 corresp0nd <46357632+corresp0nd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using Content.Shared._Impstation.Thaven;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Impstation.Thaven.Eui;

[GenerateTypedNameReferences]
public sealed partial class MoodContainer : BoxContainer
{
    public MoodContainer(ThavenMood? mood = null)
    {
        RobustXamlLoader.Load(this);

        if (mood != null)
        {
            ThavenMoodTitle.Text = mood.GetLocName();
            ThavenMoodContent.TextRope = new Rope.Leaf(mood.GetLocDesc());
        }
    }
}
