- type: entity
  id: MusicTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: music techfab machine board
  description: A machine printed circuit board for a music techfab.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: MusicTechFab
    stackRequirements:
      MatterBin: 2
      Manipulator: 2
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker
