# SPDX-FileCopyrightText: 2025 Gansu <68031780+GansuLalan@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 aa5g21 <aa5g21@soton.ac.uk>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  id: MusicTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: music techfab machine board
  description: A machine printed circuit board for a music techfab.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: MusicTechFab
    stackRequirements:
      MatterBin: 2
      Manipulator: 2
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker
