// SPDX-FileCopyrightText: 2025 TrixxedHeart <46364955+TrixxedBit@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 qrwas <55228920+qrwas@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Lobby.UI.Loadouts;

/// <summary>
/// A button that toggles the loadout groups. Needs for override default styles.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ToggleLoadoutButton : Button;
