// SPDX-FileCopyrightText: 2025 Steve <marlumpy@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Genetics.Events;
using Content.Shared._Funkystation.Genetics.Components;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Utility;
using System.Linq;
using System.Runtime.CompilerServices;
using static Robust.Client.Graphics.StyleBox;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Genetics.GeneticAnalyzer;

[Virtual]
[GenerateTypedNameReferences]
public sealed partial class GeneticAnalyzerWindow : FancyWindow
{
    public event Action? OnPrintPressed;

    private static readonly VectorFont FontBold = new(
        IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf"), 14);

    private static readonly VectorFont FontRegular = new(
        IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf"), 14);

    public GeneticAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    public void Populate(GeneticAnalyzerUiState state)
    {
        Clear();

        if (string.IsNullOrEmpty(state.PatientName))
        {
            NoPatientDataText.Visible = true;
            MainContainer.Visible = false;
            ScrollContainer.Visible = false;
            return;
        }

        NoPatientDataText.Visible = false;
        MainContainer.Visible = true;
        ScrollContainer.Visible = true;
        PatientNameLabel.Text = state.PatientName;
        StatsLabel.Text = StatsLabel.Text = state.PatientInstability.ToString();

        SequenceContainer.RemoveAllChildren();

        var sortedMutations = state.Mutations?
            .Where(m => m.Block > 0)
            .OrderBy(m => m.Block)
            .ToList() ?? new();

        if (!sortedMutations.Any())
        {
            var noBlocksLabel = new Label
            {
                Text = Loc.GetString("genetic-analyzer-no-enzymes")
            };
            SequenceContainer.AddChild(noBlocksLabel);
            return;
        }

        foreach (var mut in sortedMutations)
        {
            var displayName = state.DiscoveredIds.Contains(mut.Id)
                ? mut.Name
                : Loc.GetString("genetic-analyzer-unknown-mutation", ("block", mut.Block));

            var blockLine = new BoxContainer { Orientation = LayoutOrientation.Vertical };

            var blockLabel = new Label
            {
                Text = $"{displayName}:",
                FontOverride = mut.Enabled ? FontBold : FontRegular
            };

            var seqLabel = new Label
            {
                Text = FormatSequence(mut.RevealedSequence),
                HorizontalExpand = true,
                Margin = new Thickness(10, 0, 0, 0)
            };

            blockLine.AddChild(blockLabel);
            blockLine.AddChild(seqLabel);
            SequenceContainer.AddChild(blockLine);
        }
    }

    private static string FormatSequence(string seq)
    {
        if (string.IsNullOrEmpty(seq))
            return seq;

        const int groupSize = 8;
        var sb = new System.Text.StringBuilder(seq.Length + (seq.Length / groupSize));
        for (int i = 0; i < seq.Length; i++)
        {
            if (i > 0 && i % groupSize == 0)
                sb.Append('-');
            sb.Append(seq[i]);
        }
        return sb.ToString();
    }

    private void Clear()
    {
        PatientNameLabel.Text = Loc.GetString("genetic-analyzer-scanning");
        StatsLabel.Text = "";
        NoPatientDataText.Visible = true;
        MainContainer.Visible = false;
        ScrollContainer.Visible = false;
        SequenceContainer.RemoveAllChildren();
    }
}
