// SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Tojo <32783144+Alecksohs@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class VendingMachineEntry : BoxContainer, IListEntry
{
    public VendingMachineEntry(ListData data, int index)
    {
        RobustXamlLoader.Load(this);
        Data = data;
        Index = index;
        ControlRoot = this;
        ButtonRef = ButtonLabel;
    }

    public void Init(EntProtoId entProto, string text, int count)
    {
        ItemPrototype.SetPrototype(entProto);

        NameLabel.Text = text;
        CountLabel.Text = count.ToString();
        CountLabel.FontColorOverride = count > 0 ? Color.WhiteSmoke : Color.DimGray;
    }


    public EntityUid? UiEntity { get; }
    public ListData Data { get; }
    public int Index { get; }
    public Control ControlRoot { get; }
    public BaseButton ButtonRef { get; }
}
