# SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 pa.pecherskij <pa.pecherskij@interfax.ru>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: localizedDataset
  id: NamesFirst
  values:
    prefix: names-first-dataset-
    count: 1395

- type: localizedDataset
  id: NamesLast
  values:
    prefix: names-last-dataset-
    count: 553
