using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Funkystation.Payouts;

[GenerateTypedNameReferences]
public sealed partial class PaymentRecordButton : ItemList.Item
{
    public string? CharacterNameText = null;
    public string? PayoutStatusText = null;

    public uint? KeySelected = null;
    
    public PaymentRecordButton()
    {
        CharacterName.Text = CharacterNameText;
        PayoutStatus.Text = PayoutStatusText;
    }
}