// SPDX-FileCopyrightText: 2026 Steve <marlumpy@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Content.Shared.Atmos.Prototypes;
using Content.Shared._Funkystation.Cargo.Components;
using Content.Shared._Funkystation.Atmos.Components;

namespace Content.Client._Funkystation.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GasExtractorTabContent : BoxContainer
    {
        [Dependency] private readonly IEntityManager _entMan = default!;
        [Dependency] private readonly IPrototypeManager _proto = default!;

        private EntityUid? _consoleUid;
        public event Action<int, float, float>? OnGasExtractorSetSettings;
        public event Action<int, bool>? OnToggleAutoBuyExtractor;
        public event Action<int, int>? OnBuyMolesForExtractor;

        public GasExtractorTabContent()
        {
            RobustXamlLoader.Load(this);
        }

        public void SetConsole(EntityUid consoleUid)
        {
            _consoleUid = consoleUid;
            RefreshExtractors();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            // Update all extractor row statuses
            for (int i = 0; i < GasExtractorsListContainer.ChildCount; i++)
            {
                if (GasExtractorsListContainer.Children[i] is GasExtractorRow row &&
                    _consoleUid.HasValue &&
                    _entMan.TryGetComponent<GasExtractorConsoleComponent>(_consoleUid.Value, out var console))
                {
                    if (i < console.LinkedExtractors.Count)
                    {
                        var extractorUid = console.LinkedExtractors[i];
                        UpdateExtractorRowStatus(row, extractorUid);

                        if (_entMan.TryGetComponent<GasExtractorComponent>(extractorUid, out var extractor))
                        {
                            row.RemainingMolesLabel.Text = Loc.GetString("gas-extractor-remaining-moles",
                                ("amount", extractor.RemainingMoles.ToString("N1")));
                        }
                    }
                }
            }
        }

        public void RefreshExtractors()
        {
            GasExtractorsListContainer.RemoveAllChildren();

            if (!_consoleUid.HasValue || !_entMan.EntityExists(_consoleUid.Value))
                return;

            if (!_entMan.TryGetComponent<GasExtractorConsoleComponent>(_consoleUid.Value, out var gasConsole))
                return;

            var currentLinkedExtractors = new HashSet<EntityUid>(gasConsole.LinkedExtractors);
            int extractorIndex = 0;

            foreach (var sinkUid in currentLinkedExtractors)
            {
                if (!_entMan.EntityExists(sinkUid))
                    continue;

                if (!_entMan.TryGetComponent<GasExtractorComponent>(sinkUid, out var extractor))
                    continue;

                string protoId = ((int)extractor.SpawnGas).ToString();
                string gasName = extractor.SpawnGas.ToString();
                float pricePerMole = 0f;

                if (_proto.TryIndex<GasPrototype>(protoId, out var gasProto))
                    pricePerMole = gasProto.PricePerMole;

                var row = new GasExtractorRow();
                row.GasNameLabel.Text = gasName;

                row.RateSpinBox.Value = (int)extractor.SpawnAmount;
                row.MaxPressureSpinBox.Value = (int)extractor.MaxExternalPressure;

                row.RateSpinBox.ValueChanged += args =>
                {
                    row.ApplyButton.Disabled = false;
                };

                row.MaxPressureSpinBox.ValueChanged += args =>
                {
                    row.ApplyButton.Disabled = false;
                };

                row.BuyPreviewLabel.Text = $"[color=#a0d0ff]{Loc.GetString("gas-extractor-price-per-mol", ("price", pricePerMole.ToString("F2")))}[/color]";

                row.RemainingMolesLabel.Text = Loc.GetString("gas-extractor-remaining-moles",
                    ("amount", extractor.RemainingMoles.ToString("N1")));

                // Apply button sends final values to server
                int currentIndex = extractorIndex;
                row.ApplyButton.OnPressed += _ =>
                {
                    int rateToSend = GetClampedValue(row.RateSpinBox);
                    int pressureToSend = GetClampedValue(row.MaxPressureSpinBox);

                    // Send to server
                    OnGasExtractorSetSettings?.Invoke(currentIndex, rateToSend, pressureToSend);

                    // Immediately update UI to match what was sent
                    row.RateSpinBox.Value = rateToSend;
                    row.MaxPressureSpinBox.Value = pressureToSend;

                    float finalCredits = rateToSend * pricePerMole;
                    row.ApplyButton.Disabled = true;
                };

                row.AutoBuyCheckBox.Pressed = extractor.AutoBuyEnabled;
                row.AutoBuyCheckBox.OnToggled += (args) =>
                {
                    OnToggleAutoBuyExtractor?.Invoke(currentIndex, args.Pressed);
                };

                row.BuySpinBox.Value = 100;
                row.BuyButton.OnPressed += _ =>
                {
                    var moles = (int)Math.Max(0, row.BuySpinBox.Value);
                    if (moles > 0)
                    {
                        OnBuyMolesForExtractor?.Invoke(currentIndex, moles);
                    }
                };

                UpdateExtractorRowStatus(row, sinkUid);

                GasExtractorsListContainer.AddChild(row);
                extractorIndex++;
            }
        }

        private void UpdateExtractorRowStatus(GasExtractorRow row, EntityUid extractorUid)
        {
            if (!_entMan.TryGetComponent<GasExtractorComponent>(extractorUid, out var extractor))
                return;

            string text;
            Color color;

            switch (extractor.ExtractorState)
            {
                case GasExtractorState.Disabled:
                    text = Loc.GetString("gas-extractor-state-disabled");
                    color = Color.Red;
                    break;
                case GasExtractorState.Idle:
                    text = Loc.GetString("gas-extractor-state-idle");
                    color = Color.Yellow;
                    break;
                case GasExtractorState.Working:
                    text = Loc.GetString("gas-extractor-state-working");
                    color = Color.Green;
                    break;
                default:
                    text = "";
                    color = Color.Gray;
                    break;
            }

            row.SetStatus(text, color);
        }

        private static int GetClampedValue(SpinBox spinBox)
        {
            var text = spinBox.LineEditControl.Text;

            if (string.IsNullOrWhiteSpace(text))
                return 0;

            return int.TryParse(text, out int value)
                ? Math.Clamp(value, 0, 4500)
                : 0;
        }
    }
}
