using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Client.Cargo.UI;

namespace Content.Client._Funkystation.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GasMinerRow : PanelContainer
    {
        public GasMinerRow()
        {
            RobustXamlLoader.Load(this);
        }

        /// <summary>
        /// Sets the status text and color.
        /// </summary>
        public void SetStatus(string text, Color color)
        {
            StatusLabel.Text = text;
            StatusLabel.Modulate = color;
        }
    }
}
