using Robust.Client.AutoGenerated;
using Content.Shared.Atmos.Components;
using Content.Shared.DeviceLinking;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Cargo.Components;
using Content.Shared._Funkystation.Cargo.Components;
using Content.Client.Cargo.UI;

namespace Content.Client._Funkystation.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GasMinerTabContent : BoxContainer
    {
        [Dependency] private readonly IEntityManager _entMan = default!;
        [Dependency] private readonly IPrototypeManager _proto = default!;

        private EntityUid? _consoleUid;
        public event Action<int, float, float>? OnGasMinerSetSettings;
        public event Action<int, bool>? OnToggleAutoBuyMiner;
        public event Action<int, int>? OnBuyMolesForMiner;
        private static readonly string[] GasLocalizedNames = new[]
        {
            Loc.GetString("gases-oxygen"),        // 0 - Oxygen
            Loc.GetString("gases-nitrogen"),      // 1 - Nitrogen
            Loc.GetString("gases-co2"),           // 2 - Carbon Dioxide
            Loc.GetString("gases-plasma"),        // 3 - Plasma
            Loc.GetString("gases-tritium"),       // 4 - Tritium
            Loc.GetString("gases-water-vapor"),   // 5 - Water Vapor
            Loc.GetString("gases-ammonia"),       // 6 - Ammonia
            Loc.GetString("gases-n2o"),           // 7 - Nitrous Oxide
            Loc.GetString("gases-frezon"),        // 8 - Frezon
            Loc.GetString("gases-bz"),            // 9 - BZ
            Loc.GetString("gases-healium"),       // 10 - Healium
            Loc.GetString("gases-nitrium"),       // 11 - Nitrium
            Loc.GetString("gases-pluoxium"),      // 12 - Pluoxium
            Loc.GetString("gases-hydrogen"),      // 13 - Hydrogen
            Loc.GetString("gases-hyper-noblium"), // 14 - Hyper-Noblium
            Loc.GetString("gases-proto-nitrate"), // 15 - Proto-Nitrate
            Loc.GetString("gases-zauker"),        // 16 - Zauker
            Loc.GetString("gases-halon"),         // 17 - Halon
            Loc.GetString("gases-helium"),        // 18 - Helium
            Loc.GetString("gases-anti-noblium")   // 19 - Anti-Noblium
        };

        public GasMinerTabContent()
        {
            RobustXamlLoader.Load(this);
        }

        public void SetConsole(EntityUid consoleUid)
        {
            _consoleUid = consoleUid;
            RefreshMiners();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            // Update all miner row statuses
            for (int i = 0; i < GasMinersListContainer.ChildCount; i++)
            {
                if (GasMinersListContainer.Children[i] is GasMinerRow row &&
                    _consoleUid.HasValue &&
                    _entMan.TryGetComponent<GasMinerConsoleComponent>(_consoleUid.Value, out var console))
                {
                    if (i < console.LinkedMiners.Count)
                    {
                        var minerUid = console.LinkedMiners[i];
                        UpdateMinerRowStatus(row, minerUid);

                        if (_entMan.TryGetComponent<GasMinerComponent>(minerUid, out var miner))
                        {
                            row.RemainingMolesLabel.Text = Loc.GetString("gas-miner-remaining-moles",
                                ("amount", miner.RemainingMoles.ToString("N1")));
                        }
                    }
                }
            }
        }

        public void RefreshMiners()
        {
            GasMinersListContainer.RemoveAllChildren();

            if (!_consoleUid.HasValue || !_entMan.EntityExists(_consoleUid.Value))
                return;

            if (!_entMan.TryGetComponent<GasMinerConsoleComponent>(_consoleUid.Value, out var gasConsole))
                return;

            var currentLinkedMiners = new HashSet<EntityUid>(gasConsole.LinkedMiners);
            int minerIndex = 0;

            foreach (var sinkUid in currentLinkedMiners)
            {
                if (!_entMan.EntityExists(sinkUid))
                    continue;

                if (!_entMan.TryGetComponent<GasMinerComponent>(sinkUid, out var miner))
                    continue;

                string protoId = ((int)miner.SpawnGas).ToString();
                string gasName = $"Unknown Gas ({miner.SpawnGas})";
                float pricePerMole = 0f;

                if (_proto.TryIndex<GasPrototype>(protoId, out var gasProto))
                {
                    gasName = Loc.GetString(gasProto.Name);
                    pricePerMole = gasProto.PricePerMole;
                }

                var row = new GasMinerRow();
                row.GasNameLabel.Text = gasName;

                row.RateSpinBox.Value = (int)miner.SpawnAmount;
                row.MaxPressureSpinBox.Value = (int)miner.MaxExternalPressure;

                row.RateSpinBox.ValueChanged += args =>
                {
                    row.ApplyButton.Disabled = false;
                };

                row.MaxPressureSpinBox.ValueChanged += args =>
                {
                    row.ApplyButton.Disabled = false;
                };

                row.BuyPreviewLabel.Text = $"[color=#a0d0ff]{Loc.GetString("gas-miner-price-per-mol", ("price", pricePerMole.ToString("F2")))}[/color]";

                row.RemainingMolesLabel.Text = Loc.GetString("gas-miner-remaining-moles", ("amount", miner.RemainingMoles.ToString("N1")));

                // Apply button sends final values to server
                int currentIndex = minerIndex;
                row.ApplyButton.OnPressed += _ =>
                {
                    int rateToSend = GetClampedValue(row.RateSpinBox);
                    int pressureToSend = GetClampedValue(row.MaxPressureSpinBox);

                    // Send to server
                    OnGasMinerSetSettings?.Invoke(currentIndex, rateToSend, pressureToSend);

                    // Immediately update UI to match what was sent
                    row.RateSpinBox.Value = rateToSend;
                    row.MaxPressureSpinBox.Value = pressureToSend;

                    float finalCredits = rateToSend * pricePerMole;
                    row.ApplyButton.Disabled = true;
                };

                row.AutoBuyCheckBox.Pressed = miner.AutoBuyEnabled;
                row.AutoBuyCheckBox.OnToggled += (args) =>
                {
                    OnToggleAutoBuyMiner?.Invoke(currentIndex, args.Pressed);
                };

                row.BuySpinBox.Value = 100;
                row.BuyButton.OnPressed += _ =>
                {
                    var spesos = (int)Math.Max(0, row.BuySpinBox.Value);
                    if (spesos > 0)
                    {
                        OnBuyMolesForMiner?.Invoke(currentIndex, spesos);
                    }
                };

                UpdateMinerRowStatus(row, sinkUid);

                GasMinersListContainer.AddChild(row);
                minerIndex++;
            }
        }

        private void UpdateMinerRowStatus(GasMinerRow row, EntityUid minerUid)
        {
            if (!_entMan.TryGetComponent<GasMinerComponent>(minerUid, out var miner))
                return;

            string text;
            Color color;

            switch (miner.MinerState)
            {
                case GasMinerState.Disabled:
                    text = Loc.GetString("gas-miner-state-disabled");
                    color = Color.Red;
                    break;
                case GasMinerState.Idle:
                    text = Loc.GetString("gas-miner-state-idle");
                    color = Color.Orange;
                    break;
                case GasMinerState.Working:
                    text = Loc.GetString("gas-miner-state-working");
                    color = Color.Green;
                    break;
                default:
                    text = "";
                    color = Color.Gray;
                    break;
            }

            row.SetStatus(text, color);
        }

        private static int GetClampedValue(SpinBox spinBox)
        {
            var text = spinBox.LineEditControl.Text;

            if (string.IsNullOrWhiteSpace(text))
                return 0;

            return int.TryParse(text, out int value)
                ? Math.Clamp(value, 0, 4500)
                : 0;
        }
    }
}
