using Content.Client.Stylesheets;
using Content.Shared._Funkystation.Medical.SmartFridge;
using Content.Shared.Wires;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Funkystation.Medical.SmartFridge.UI;

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeItem : BoxContainer
{
    public event Action<BaseButton.ButtonEventArgs, DispenseButton>? OnDispenseButtonPressed;
    public SmartFridgeItem(EntProtoId entProto, string name, string quantity, bool addDispenseButtons)
    {
        RobustXamlLoader.Load(this);

        //this calls the separated button builder, and stores the return to render after labels
        var dispenseButtonConstructors = CreateDispenseButtons(addDispenseButtons);

        ItemPrototype.SetPrototype(entProto);
        NameLabel.Text = name;
        NameQuantity.Text = quantity;

        // Adds the dispense buttons after
        foreach (var dispenseButton in dispenseButtonConstructors)
        {
            PrimaryContainer.AddChild(dispenseButton);
        }
    }

    private DispenseButton MakeDispenseButton(string text, FridgeAmount amount, string styleClass)
    {
        var button = new DispenseButton(text, amount, styleClass);
        button.OnPressed += args
            => OnDispenseButtonPressed?.Invoke(args, button);
        return button;
    }

    /// <summary>
    /// Conditionally generates a set of dispenser buttons based on the supplied boolean argument.
    /// </summary>
    private List<DispenseButton> CreateDispenseButtons(bool addDispenseButtons)
    {
        if (!addDispenseButtons)
            return new List<DispenseButton>(); // Return an empty list if addDispenseButton creation is disabled.

        var buttonConfigs = new (string text, FridgeAmount amount, string styleClass)[]
        {
            ("1", FridgeAmount.E1, StyleBase.ButtonOpenRight),
            ("2", FridgeAmount.E2, StyleBase.ButtonOpenBoth),
            ("5", FridgeAmount.E5, StyleBase.ButtonOpenBoth),
            ("10", FridgeAmount.E10, StyleBase.ButtonOpenBoth),
            ("15", FridgeAmount.E15, StyleBase.ButtonOpenBoth),
            (Loc.GetString("chem-master-window-buffer-all-amount"), FridgeAmount.All, StyleBase.ButtonOpenLeft),
        };
        var buttons = new List<DispenseButton>();

        foreach (var (text, amount, styleClass) in buttonConfigs)
        {
            var dispenseButton = MakeDispenseButton(text, amount, styleClass);
            buttons.Add(dispenseButton);
        }

        return buttons;
    }

    public sealed class DispenseButton : Button
    {
        public FridgeAmount Amount { get; set; }
        public DispenseButton(string text, FridgeAmount amount, string styleClass)
        {
            AddStyleClass(styleClass);
            Text = text;
            Amount = amount;
        }
    }
}
