using Content.Client.UserInterface.Controls;
using Content.Shared.Ghost;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Manifest;

[GenerateTypedNameReferences]
public sealed partial class DeathInformationWindow : FancyWindow
{
    [Dependency] private readonly IPlayerManager _players = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    private SharedMindSystem? _mind;

    private readonly int _characterLimit = 64;
    public event Action<string>? OnSubmitted;

    public DeathInformationWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SubmitButton.OnPressed += _ => OnSubmitted?.Invoke(Rope.Collapse(DeathInformationWindowTextEdit.TextRope));
        DeathInformationWindowTextEdit.OnTextChanged += _ => UpdateWordCount();
    }

    private void UpdateWordCount()
    {
        SubmitButton.Disabled = DeathInformationWindowTextEdit.TextLength > _characterLimit;
        CharacterLimitLabel.Text = DeathInformationWindowTextEdit.TextLength + "/" + _characterLimit;
    }

}


