# SPDX-FileCopyrightText: 2024 John Space <bigdumb421@gmail.com>
# SPDX-FileCopyrightText: 2024 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  id: BaseMechWeaponMelee
  parent: BaseMechEquipment
  abstract: true
  components:
  - type: Appearance
  - type: StaticPrice
    price: 1
  - type: Item
    size: Ginormous
  - type: MultiHandedItem
  - type: ClothingSpeedModifier
    walkModifier: 0.5
    sprintModifier: 0.5
  - type: HeldSpeedModifier
