// SPDX-FileCopyrightText: 2026 Steve <marlumpy@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Globalization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Atmos.Piping.Binary.UI;

/// <summary>
/// Client-side window for configuring a temperature gate device.
/// Handles threshold input, mode toggle, and enabled status.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TemperatureGateWindow : DefaultWindow
{
    private bool _enabled;
    private float _threshold;
    private bool _isMinMode;

    public event Action<bool>? OnStatusToggled;
    public event Action<float, bool>? OnThresholdAndModeSet;

    public TemperatureGateWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleStatusButton.OnPressed += _ =>
        {
            OnStatusToggled?.Invoke(_enabled);
        };

        ThresholdInput.OnTextChanged += _ => UpdateApplyButtonState();

        ToggleModeButton.OnPressed += _ =>
        {
            // Apply immediately for snappy feel
            _isMinMode = !_isMinMode;
            UpdateModeButton();
            UpdateApplyButtonState();

            // Send the new local value to server
            OnThresholdAndModeSet?.Invoke(GetCurrentThreshold(), _isMinMode);
        };

        SetButton.OnPressed += _ =>
        {
            if (TryParseThreshold(out var newThreshold))
            {
                OnThresholdAndModeSet?.Invoke(newThreshold, _isMinMode);
                UpdateApplyButtonState();
            }
        };

        UpdateVisuals(); // initial state
    }

    /// <summary>
    /// Syncs the window UI with the current server values.
    /// Called from BUI whenever networked state arrives
    /// </summary>
    public void UpdateUI(bool enabled, float threshold, bool isMinMode)
    {
        _enabled = enabled;
        _threshold = threshold;
        _isMinMode = isMinMode;

        ThresholdInput.Text = threshold.ToString("F2");

        UpdateVisuals();
    }

    /// <summary>
    /// Updates the visual state of all UI elements (status button, mode button, apply button).
    /// Called after any change to enabled, threshold, or mode.
    /// </summary>
    private void UpdateVisuals()
    {
        UpdateStatusButton();
        UpdateModeButton();
        UpdateApplyButtonState();
    }

    /// <summary>
    /// Refreshes the enabled/disabled text on the toggle status button based on the current _enabled value.
    /// </summary>
    private void UpdateStatusButton()
    {
        ToggleStatusButton.Text = _enabled
            ? Loc.GetString("temperature-gate-ui-status-enabled")
            : Loc.GetString("temperature-gate-ui-status-disabled");
        ToggleStatusButton.Pressed = _enabled;
    }

    /// <summary>
    /// Updates the mode toggle button text to reflect the current min/max mode (_isMinMode).
    /// </summary>
    private void UpdateModeButton()
    {
        ToggleModeButton.Text = _isMinMode
            ? Loc.GetString("temperature-gate-ui-mode-min")
            : Loc.GetString("temperature-gate-ui-mode-max");
    }

    /// <summary>
    /// Enables or disables the "Set" button based on whether the current input represents a valid change
    /// from the last known threshold value. Called whenever the threshold input text changes or mode flips.
    /// </summary>
    private void UpdateApplyButtonState()
    {
        if (!TryParseThreshold(out var currentInput))
        {
            SetButton.Disabled = true;
            return;
        }

        // Enable if the input value is different from the current threshold state
        var thresholdChanged = currentInput != _threshold;
        SetButton.Disabled = !thresholdChanged;
    }

    /// <summary>
    /// Attempts to parse the threshold input field as a float.
    /// </summary>
    private bool TryParseThreshold(out float value)
    {
        value = 0f;
        var text = ThresholdInput.Text?.Trim();

        if (string.IsNullOrWhiteSpace(text))
            return false;

        return float.TryParse(text, NumberStyles.Float | NumberStyles.AllowDecimalPoint,
            CultureInfo.InvariantCulture, out value);
    }

    /// <summary>
    /// Gets the current threshold from the input field, falling back to the last known valid value if parsing fails.
    /// </summary>
    private float GetCurrentThreshold()
    {
        return float.TryParse(ThresholdInput.Text?.Trim(), NumberStyles.Float | NumberStyles.AllowDecimalPoint,
            CultureInfo.InvariantCulture, out var parsed)
            ? parsed
            : _threshold;
    }
}
