using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Genetics;
using Content.Shared._Funkystation.Genetics.Components;
using Content.Shared._Funkystation.Genetics.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.Manager.Exceptions;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Funkystation.Genetics.DnaScannerConsole.UI;

[Virtual]
[GenerateTypedNameReferences]
public sealed partial class DnaScannerConsoleWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IInputManager  _input = default!;

    private readonly char[] _bases = { 'X', 'A', 'T', 'G', 'C' };
    private readonly Button[] _sequencerButtons = new Button[32];

    private List<Button> _mutationButtons = new();
    private List<MutationEntry>? _currentMutations;
    private List<MutationEntry> _savedMutations = new();

    private string? _selectedMutationId;
    private bool _isSelectedMutationStored;

    private Button? _currentlyPressedButton;
    private HashSet<string>? _discoveredMutationIds;

    private bool _isSubjectDead;

    public event Action<int, char, string>? OnSequencerButtonPressed;
    public event Action<string>? OnSaveMutationPressed;
    public event Action<string>? OnDeleteMutationPressed;
    public event Action<string>? OnPrintActivatorPressed;
    public event Action<string>? OnPrintMutatorPressed;
    public event Action? OnScrambleDnaPressed;

    private static readonly VectorFont FontBold = new(
        IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf"), 14);

    private static readonly VectorFont FontRegular = new(
        IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf"), 14);

    public DnaScannerConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SetupSequencerButtons();

        SaveMutationButton.OnPressed += _ => TryInvokeSelected(OnSaveMutationPressed);
        DeleteMutationButton.OnPressed += _ => TryInvokeSelected(OnDeleteMutationPressed);
        PrintActivatorButton.OnPressed += _ => TryInvokeSelected(OnPrintActivatorPressed);
        PrintMutatorButton.OnPressed += _ => TryInvokeSelected(OnPrintMutatorPressed);
        ScrambleDnaButton.OnPressed += _ => OnScrambleDnaPressed?.Invoke();
    }

    private void SetupSequencerButtons()
    {
        var buttons = new[]
        {
            Seq_1, Seq_2, Seq_3, Seq_4, Seq_5, Seq_6, Seq_7, Seq_8,
            Seq_9, Seq_10, Seq_11, Seq_12, Seq_13, Seq_14, Seq_15, Seq_16,
            Seq_17, Seq_18, Seq_19, Seq_20, Seq_21, Seq_22, Seq_23, Seq_24,
            Seq_25, Seq_26, Seq_27, Seq_28, Seq_29, Seq_30, Seq_31, Seq_32
        };

        for (int i = 0; i < buttons.Length; i++)
        {
            _sequencerButtons[i] = buttons[i];
            var index = i;
            buttons[i].OnPressed += _ => CycleBase(index);
        }
    }

    public void UpdateSubjectInfo(
        string? name,
        string? health,
        float? geneticDamage,
        int instability,
        TimeSpan? scrambleCooldownEnd)
    {
        var hasSubject = name != null;
        SubjectNameLabel.Text = hasSubject ? name : "";
        SubjectInfoBox.Visible = hasSubject;

        HealthLabel.Text = health ?? "--";
        GeneticDamageLabel.Text = geneticDamage?.ToString() ?? "--";
        GeneticInstabilityLabel.Text = instability.ToString();

        _isSubjectDead = health == "Dead";

        UpdateScrambleButtonState(scrambleCooldownEnd);
    }

    public void UpdateGeneticsTab(List<MutationEntry>? mutations, HashSet<string>? baseMutationIds)
    {
        NoSequencesLabel.Visible = mutations == null || mutations.Count == 0;
        SequencesContainer.Visible = mutations?.Count > 0;

        BaseSequencesContainer.RemoveAllChildren();
        AddedSequencesContainer.RemoveAllChildren();
        _mutationButtons.Clear();
        _currentMutations = mutations;

        ClearMutationDetails();
        UpdateRightPanelVisibilityAndButtons();

        if (mutations == null || mutations.Count == 0)
            return;

        var baseIds = baseMutationIds ?? new HashSet<string>();
        int index = 0;

        foreach (var mut in mutations)
        {
            var isDiscovered = _discoveredMutationIds?.Contains(mut.Id) ?? false;
            var displayName = isDiscovered ? mut.Name : $"Mutation {mut.Block:00}";

            var button = new Button
            {
                Text = displayName,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
                StyleClasses = { "ListItemButton" }
            };

            var capturedIndex = index;
            button.OnPressed += _ => SelectMutation(capturedIndex);

            _mutationButtons.Add(button);

            var container = baseIds.Contains(mut.Id) ? BaseSequencesContainer : AddedSequencesContainer;
            container.AddChild(button);

            // Restore selection if needed
            if (mut.Id == _selectedMutationId && !_isSelectedMutationStored)
            {
                _currentlyPressedButton = button;
                button.Pressed = true;
                UpdateMutationDetails(mut);
                LoadMutationSequence(mut.RevealedSequence);
                UpdatePrintSaveButtonState();
            }

            index++;
        }

        BaseSequencesCollapsible.Visible = BaseSequencesContainer.ChildCount > 0;
        AddedSequencesCollapsible.Visible = AddedSequencesContainer.ChildCount > 0;
    }

    public void UpdateDiscoveredMutations(HashSet<string> discoveredIds)
    {
        _discoveredMutationIds = discoveredIds;
        RefreshSelectedMutationDetails();
        RefreshAllMutationButtonTexts();
    }

    public void UpdateSavedMutations(List<MutationEntry> savedMutations)
    {
        StoredSequencesContainer.RemoveAllChildren();
        NoSavedSequencesLabel.Visible = savedMutations.Count == 0;

        _savedMutations = savedMutations;

        if (savedMutations.Count == 0)
            return;

        foreach (var mut in savedMutations)
        {
            var button = new Button
            {
                Text = mut.Name,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
                StyleClasses = { "ListItemButton" }
            };

            button.OnPressed += _ =>
            {
                if (_currentlyPressedButton != null)
                    _currentlyPressedButton.Pressed = false;

                _currentlyPressedButton = button;
                button.Pressed = true;

                _selectedMutationId = mut.Id;
                _isSelectedMutationStored = true;

                UpdateMutationDetails(mut);
                LoadMutationSequence(mut.RevealedSequence);
                UpdatePrintSaveButtonState();
                UpdateSequencerButtonsState();
                UpdateRightPanelVisibilityAndButtons();
            };

            StoredSequencesContainer.AddChild(button);
        }
    }

    private void SelectMutation(int index)
    {
        if (_currentMutations == null || index < 0 || index >= _currentMutations.Count)
            return;

        if (_currentlyPressedButton != null)
            _currentlyPressedButton.Pressed = false;

        var selectedButton = _mutationButtons[index];
        selectedButton.Pressed = true;
        _currentlyPressedButton = selectedButton;

        var mutation = _currentMutations[index];
        _selectedMutationId = mutation.Id;
        _isSelectedMutationStored = false;

        UpdateMutationDetails(mutation);
        LoadMutationSequence(mutation.RevealedSequence);
        UpdatePrintSaveButtonState();
        UpdateSequencerButtonsState();
        UpdateRightPanelVisibilityAndButtons();
    }

    private void UpdateMutationDetails(MutationEntry mutation)
    {
        var isDiscovered = _discoveredMutationIds?.Contains(mutation.Id) ?? false;
        var isActive = mutation.RevealedSequence == mutation.OriginalSequence;
        string displayName = isDiscovered ? mutation.Name : $"Mutation {mutation.Block:00}";

        if (isActive)
            InfoNameLabel.Text = $"{displayName} (Active)";
        else
            InfoNameLabel.Text = displayName;

        // Only show "(Active)" if discovered, otherwise it looks weird
        if (isActive && isDiscovered)
            displayName += " (Active)";

        InfoDescLabel.Text = isDiscovered ? (mutation.Description ?? "No description.") : "Undiscovered mutation.";
        InfoInstabilityLabel.Text = isDiscovered ? mutation.Instability.ToString() : "Unknown";
        UpdateConflictsDisplay(mutation);
    }

    private void UpdateConflictsDisplay(MutationEntry mutation)
    {
        var isDiscovered = _discoveredMutationIds?.Contains(mutation.Id) ?? false;

        if (mutation.Conflicts is not { Count: > 0 } conflicts ||
            _discoveredMutationIds is not { } discovered ||
            !isDiscovered)
        {
            ConflictsLabelContainer.Visible = false;
            return;
        }

        var knownNames = new List<string>();

        foreach (var conflictId in conflicts)
        {
            if (!discovered.Contains(conflictId))
                continue;

            if (IoCManager.Resolve<IPrototypeManager>()
                    .TryIndex<GeneticMutationPrototype>(conflictId, out var proto))
            {
                knownNames.Add(proto.Name);
            }
        }

        if (knownNames.Count == 0)
        {
            ConflictsLabelContainer.Visible = false;
            return;
        }

        knownNames.Sort();
        ConflictsLabel.Text = string.Join(", ", knownNames);
        ConflictsLabelContainer.Visible = true;
    }

    private void RefreshSelectedMutationDetails()
    {
        if (_selectedMutationId == null)
            return;

        var mutation = _currentMutations?.Find(m => m.Id == _selectedMutationId)
                       ?? _savedMutations.Find(m => m.Id == _selectedMutationId);

        if (mutation != null)
            UpdateMutationDetails(mutation);
    }

    private void RefreshAllMutationButtonTexts()
    {
        if (_currentMutations == null || _mutationButtons.Count != _currentMutations.Count)
            return;

        for (int i = 0; i < _currentMutations.Count; i++)
        {
            var mut = _currentMutations[i];
            var button = _mutationButtons[i];
            var isDiscovered = _discoveredMutationIds?.Contains(mut.Id) ?? false;
            button.Text = isDiscovered ? mut.Name : $"Mutation {mut.Block:00}";
        }
    }

    private void LoadMutationSequence(string sequence)
    {
        for (int i = 0; i < 32; i++)
        {
            var c = sequence.Length > i ? sequence[i] : 'X';
            if (!_bases.Contains(c))
                c = 'X';

            var button = _sequencerButtons[i];
            button.Text = c.ToString();

            button.Modulate = c switch
            {
                'A' or 'T' => new Color(120, 255, 120),
                'G' or 'C' => new Color(100, 170, 255),
                _ => Color.White
            };
        }
    }

    private void CycleBase(int index, bool reverse = false)
    {
        var button = _sequencerButtons[index];

        if (_isSubjectDead)
        {
            // Dead subjects can't change sequence — just send current
            if (_selectedMutationId != null)
                OnSequencerButtonPressed?.Invoke(index, button.Text?[0] ?? 'X', _selectedMutationId);
            return;
        }

        var current = button.Text?.Length > 0 ? char.ToUpper(button.Text[0]) : 'X';
        int idx = Array.IndexOf(_bases, current);
        if (idx == -1)
            idx = 0;

        idx = reverse
            ? (idx == 0 ? _bases.Length - 1 : idx - 1)
            : (idx + 1) % _bases.Length;

        var newBase = _bases[idx];
        button.Text = newBase.ToString();
        button.Modulate = newBase switch
        {
            'A' or 'T' => new Color(120, 255, 120),
            'G' or 'C' => new Color(100, 170, 255),
            _ => Color.White
        };

        if (_selectedMutationId != null)
            OnSequencerButtonPressed?.Invoke(index, newBase, _selectedMutationId);
    }

    private void UpdatePrintSaveButtonState()
    {
        if (_selectedMutationId == null)
            return;

        var mutation = _currentMutations?.Find(m => m.Id == _selectedMutationId);
        var isDiscovered = _discoveredMutationIds?.Contains(_selectedMutationId) ?? false;
        var isSequenceComplete = mutation?.RevealedSequence == mutation?.OriginalSequence;

        var canPrint = isDiscovered || isSequenceComplete;

        PrintActivatorButton.Disabled = !canPrint;
        PrintMutatorButton.Disabled = !canPrint;
        SaveMutationButton.Disabled = !isSequenceComplete;

        if (_isSelectedMutationStored)
        {
            PrintActivatorButton.Disabled = false;
            PrintMutatorButton.Disabled = false;
            SaveMutationButton.Disabled = true;
        }
    }

    private void UpdateSequencerButtonsState()
    {
        var enabled = !_isSelectedMutationStored;
        foreach (var btn in _sequencerButtons)
            btn.Disabled = !enabled;
    }

    private void UpdateRightPanelVisibilityAndButtons()
    {
        var hasSelection = _selectedMutationId != null || _isSelectedMutationStored;
        InfoContainer.Visible = hasSelection;
        SequencerContainer.Visible = hasSelection;

        SaveMutationButton.Visible = !_isSelectedMutationStored;
        DeleteMutationButton.Visible = _isSelectedMutationStored;
    }

    private void UpdateScrambleButtonState(TimeSpan? cooldownEnd)
    {
        var hasSubject = SubjectInfoBox.Visible;

        if (!cooldownEnd.HasValue || cooldownEnd.Value <= _timing.CurTime)
        {
            ScrambleDnaButton.Disabled = !hasSubject;
            ScrambleDnaButton.Text = Loc.GetString("dna-scanner-scramble-dna");
            return;
        }

        var remaining = cooldownEnd.Value - _timing.CurTime;
        ScrambleDnaButton.Disabled = true;
        ScrambleDnaButton.Text = Loc.GetString("dna-scanner-scramble-cooldown",
            ("seconds", (int)remaining.TotalSeconds));
    }

    private void TryInvokeSelected(Action<string>? action)
    {
        if (_selectedMutationId != null)
            action?.Invoke(_selectedMutationId);
    }

    private void ClearMutationDetails()
    {
        InfoNameLabel.Text = "";
        InfoDescLabel.Text = "";
        InfoInstabilityLabel.Text = "";
    }
}
