// SPDX-FileCopyrightText: 2026 Steve <marlumpy@gmail.com>
// SPDX-FileCopyrightText: 2026 marc-pelletier <113944176+marc-pelletier@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Funkystation.Genetics;
using Content.Shared._Funkystation.Genetics.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Funkystation.Genetics.DnaScannerConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticistsConsoleUniqueEnzymesView : Control
{
    [Dependency] private readonly IGameTiming _timing = default!;

    // Sequencer fields
    private readonly char[] _bases = { 'A', 'T', 'G', 'C' };
    private readonly SequencerButton[] _sequencerButtons = new SequencerButton[32];

    private static readonly Color ColorAT = new(110, 255, 110);
    private static readonly Color ColorGC = new(130, 200, 255);
    private static readonly Color ActiveMutationTint = new(100, 150, 255);

    private bool _clearMode;
    private bool _jokerMode;

    // Subject mutations list fields
    private readonly List<Button> _mutationButtons = new();
    private List<MutationEntry>? _currentMutations;
    private Button? _currentlyPressedButton;

    // Selection state
    public GeneticistsConsoleWindow? ParentWindow { get; set; }
    private string? _selectedMutationId;
    private bool _isSelectedMutationStored;

    // Events raised to main window / server
    public event Action<int, char, string>? OnSequencerButtonPressed;
    public event Action? OnJokerUsed;
    public event Action<string>? OnSaveMutationPressed;
    public event Action<string>? OnPrintActivatorPressed;
    public event Action<string>? OnPrintMutatorPressed;
    public event Action<string>? OnToggleResearchPressed;

    public GeneticistsConsoleUniqueEnzymesView()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SetupSequencerButtons();

        // Sequencer buttons
        for (int i = 0; i < _sequencerButtons.Length; i++)
        {
            var button = _sequencerButtons[i];
            if (button == null) continue;

            int capturedIndex = i;
            button.OnPressed += _ => CycleBase(capturedIndex);
        }

        ClearBaseButton.OnPressed += _ => ToggleClearMode();
        JokerButton.OnPressed += _ => ToggleJokerMode();

        PrintActivatorButton.OnPressed += _ =>
        {
            if (_selectedMutationId != null)
                OnPrintActivatorPressed?.Invoke(_selectedMutationId);
        };

        PrintMutatorButton.OnPressed += _ =>
        {
            if (_selectedMutationId != null)
                OnPrintMutatorPressed?.Invoke(_selectedMutationId);
        };

        SaveMutationButton.OnPressed += _ =>
        {
            if (_selectedMutationId != null)
                OnSaveMutationPressed?.Invoke(_selectedMutationId);
        };

        ResearchMutationButton.OnPressed += _ =>
        {
            if (_selectedMutationId != null)
                OnToggleResearchPressed?.Invoke(_selectedMutationId);
        };
    }

    private void SetupSequencerButtons()
    {
        var buttons = new[]
        {
            Seq_1, Seq_2, Seq_3, Seq_4, Seq_5, Seq_6, Seq_7, Seq_8,
            Seq_9, Seq_10, Seq_11, Seq_12, Seq_13, Seq_14, Seq_15, Seq_16,
            Seq_17, Seq_18, Seq_19, Seq_20, Seq_21, Seq_22, Seq_23, Seq_24,
            Seq_25, Seq_26, Seq_27, Seq_28, Seq_29, Seq_30, Seq_31, Seq_32
        };

        for (int i = 0; i < buttons.Length; i++)
        {
            var btn = buttons[i];
            if (btn == null) continue;

            _sequencerButtons[i] = btn;
            btn.Index = i;
        }
    }

    public void UpdateGeneticsTab(List<MutationEntry>? mutations, HashSet<string>? baseMutationIds)
    {
        NoSequencesLabel.Visible = mutations == null || mutations.Count == 0;

        SequencesContainer.RemoveAllChildren();
        _mutationButtons.Clear();
        _currentMutations = mutations;

        if (mutations == null || mutations.Count == 0)
            return;

        var baseIds = baseMutationIds ?? new HashSet<string>();
        int index = 0;

        foreach (var mut in mutations)
        {
            var isDiscovered = ParentWindow?.DiscoveredMutationIds?.Contains(mut.Id) ?? false;
            var isBase = baseIds.Contains(mut.Id);

            var button = new UniqueEnzymeButton
            {
                Margin = new Thickness(1, 1, 1, 1),
                StyleClasses = { "ButtonSquare" }
            };

            button.UpdateIcon(isDiscovered, isBase);

            if (mut.Enabled)
                button.Modulate = ActiveMutationTint;
            else
                button.Modulate = Color.White;

            var capturedIndex = index;
            button.OnPressed += _ => SelectMutation(capturedIndex);

            _mutationButtons.Add(button);

            SequencesContainer.AddChild(button);

            // Restore selection if needed
            if (mut.Id == _selectedMutationId && !_isSelectedMutationStored)
            {
                _currentlyPressedButton = button;
                button.Pressed = true;
            }

            index++;
        }
    }

    private void SelectMutation(int index)
    {
        if (_currentMutations == null || index < 0 || index >= _currentMutations.Count)
            return;

        if (_currentlyPressedButton != null)
            _currentlyPressedButton.Pressed = false;

        var selectedButton = _mutationButtons[index];
        selectedButton.Pressed = true;
        _currentlyPressedButton = selectedButton;

        var mutation = _currentMutations[index];
        _selectedMutationId = mutation.Id;
        _isSelectedMutationStored = false;

        // For now we can leave the update calls here, but should be moved
        UpdateMutationDetails(mutation);
        LoadMutationSequence(mutation.RevealedSequence);
        UpdatePrintSaveButtonState();
        UpdateSequencerButtonsState();
        UpdateRightPanelVisibilityAndButtons();
        UpdateResearchButtonState();
    }

    private void LoadMutationSequence(string sequence)
    {
        for (int i = 0; i < 32; i++)
        {
            var c = sequence.Length > i ? sequence[i] : 'X';
            if (!_bases.Contains(c)) c = 'X';

            var button = _sequencerButtons[i];
            button.Text = c.ToString();

            button.Modulate = c switch
            {
                'A' or 'T' => ColorAT,
                'G' or 'C' => ColorGC,
                _ => Color.White
            };
        }
    }

    public void CycleBase(int index, bool reverse = false)
    {
        var button = _sequencerButtons[index];

        if (_jokerMode)
        {
            RevealCorrectBase(index);
            ToggleJokerMode();
            OnJokerUsed?.Invoke();
            return;
        }

        if (_clearMode)
        {
            SetBaseToX(index);
            ToggleClearMode();
            return;
        }

        if (ParentWindow is not null && (ParentWindow.IsSubjectDead ||
            _selectedMutationId is null ||
            IoCManager.Resolve<IPrototypeManager>().TryIndex<GeneticMutationPrototype>(_selectedMutationId, out var proto) &&
            proto.SequencerResistant))
        {
            if (_selectedMutationId != null)
                OnSequencerButtonPressed?.Invoke(index, button.Text?[0] ?? 'X', _selectedMutationId);
            return;
        }

        char currentChar = button.Text?.Length > 0 ? char.ToUpper(button.Text[0]) : 'X';
        int currentIndex = currentChar == 'X' || !_bases.Contains(currentChar)
            ? (reverse ? 0 : _bases.Length - 1)
            : Array.IndexOf(_bases, currentChar);

        if (currentIndex == -1) currentIndex = 0;

        int newIndex = reverse
            ? (currentIndex == 0 ? _bases.Length - 1 : currentIndex - 1)
            : (currentIndex + 1) % _bases.Length;

        char newBase = _bases[newIndex];

        button.Text = newBase.ToString();
        button.Modulate = newBase switch
        {
            'A' or 'T' => ColorAT,
            'G' or 'C' => ColorGC,
            _ => Color.White
        };

        if (_selectedMutationId != null)
            OnSequencerButtonPressed?.Invoke(index, newBase, _selectedMutationId);
    }

    private void SetBaseToX(int index)
    {
        var button = _sequencerButtons[index];
        button.Text = "X";
        button.Modulate = Color.White;

        if (_selectedMutationId != null)
            OnSequencerButtonPressed?.Invoke(index, 'X', _selectedMutationId);
    }

    private void RevealCorrectBase(int index)
    {
        var mutation = _currentMutations?.Find(m => m.Id == _selectedMutationId);
        if (mutation == null || mutation.OriginalSequence.Length <= index)
            return;

        char correctBase = mutation.OriginalSequence[index];
        if (!_bases.Contains(correctBase)) return;

        var button = _sequencerButtons[index];
        button.Text = correctBase.ToString();
        button.Modulate = correctBase switch
        {
            'A' or 'T' => ColorAT,
            'G' or 'C' => ColorGC,
            _ => Color.White
        };

        if (!_isSelectedMutationStored && _selectedMutationId != null)
            OnSequencerButtonPressed?.Invoke(index, correctBase, _selectedMutationId);
    }

    public void UpdateSequencerButtonsState()
    {
        bool enabled =
            ParentWindow != null &&
            !ParentWindow.IsSubjectDead &&
            _selectedMutationId != null &&
            !_isSelectedMutationStored;

        foreach (var btn in _sequencerButtons)
            btn.Disabled = !enabled;
    }

    private void ToggleClearMode()
    {
        _clearMode = !_clearMode;
        ClearBaseButton.Pressed = _clearMode;
    }

    private void ToggleJokerMode()
    {
        _jokerMode = !_jokerMode;
        JokerButton.Pressed = _jokerMode;
    }

    public void UpdateJokerButtonState(TimeSpan? cooldownEnd)
    {
        if (JokerButton == null) return;

        if (!cooldownEnd.HasValue || cooldownEnd.Value <= _timing.CurTime)
        {
            JokerButton.Text = Loc.GetString("dna-scanner-sequencer-joker");
            JokerButton.Disabled = ParentWindow?.IsSubjectDead ?? false || _selectedMutationId == null || _isSelectedMutationStored;
            return;
        }

        var remaining = (int)(cooldownEnd.Value - _timing.CurTime).TotalSeconds;
        JokerButton.Text = Loc.GetString("dna-scanner-joker-cooldown", ("seconds", remaining));
        JokerButton.Disabled = true;
    }

    public void UpdateDiscoveredMutations(HashSet<string>? discoveredIds)
    {
        if (ParentWindow == null)
            return;

        ParentWindow.DiscoveredMutationIds = discoveredIds;

        if (!string.IsNullOrEmpty(_selectedMutationId))
        {
            var mut = _currentMutations?.FirstOrDefault(m => m.Id == _selectedMutationId);

            if (mut != null)
                UpdateMutationDetails(mut);

            UpdatePrintSaveButtonState();
            UpdateResearchButtonState();
        }
        RefreshMutationIcons();
    }

    public void UpdateResearchData(Dictionary<string, int> remaining, Dictionary<string, int> original, HashSet<string> activeIds)
    {
        if (ParentWindow == null)
            return;

        ParentWindow.ResearchRemaining = remaining;
        ParentWindow.ResearchOriginal = original;
        ParentWindow.ActiveResearchIds = activeIds;

        UpdatePrintSaveButtonState();
        UpdateResearchButtonState();
    }

    private void UpdateMutationDetails(MutationEntry mutation)
    {
        var isKnown = IsMutationKnown(mutation);
        var isActive = mutation.Enabled;

        string displayName = isKnown ? mutation.Name : $"Mutation {mutation.Block:00}";

        if (isActive && !_isSelectedMutationStored)
            InfoNameLabel.Text = $"{displayName} (Active)";
        else
            InfoNameLabel.Text = displayName;

        InfoDescLabel.Text = isKnown ? (mutation.Description ?? "No description.") : "Undiscovered mutation.";
        InfoInstabilityLabel.Text = isKnown ? mutation.Instability.ToString() : "Unknown";

        UpdateConflictsDisplay(mutation);
        RefreshResearchLabel();
        UpdateResearchButtonState();
    }

    private void UpdateConflictsDisplay(MutationEntry mutation)
    {
        var isKnown = IsMutationKnown(mutation);

        if (!isKnown || mutation.Conflicts is not { Count: > 0 } conflicts || ParentWindow?.DiscoveredMutationIds is null)
        {
            ConflictsLabelContainer.Visible = false;
            return;
        }

        var knownNames = new List<string>();

        foreach (var conflictId in conflicts)
        {
            if (!ParentWindow.DiscoveredMutationIds.Contains(conflictId))
                continue;

            if (IoCManager.Resolve<IPrototypeManager>()
                .TryIndex<GeneticMutationPrototype>(conflictId, out var proto))
            {
                knownNames.Add(proto.Name);
            }
        }

        if (knownNames.Count == 0)
        {
            ConflictsLabelContainer.Visible = false;
            return;
        }

        knownNames.Sort();
        ConflictsLabel.Text = string.Join(", ", knownNames);
        ConflictsLabelContainer.Visible = true;
    }

    public void RefreshResearchLabel()
    {
        if (string.IsNullOrEmpty(_selectedMutationId))
        {
            InfoResearchLabel.Text = "";
            return;
        }

        // Get the current mutation entry from the subject
        var mutation = ParentWindow?.CurrentMutations?.Find(m => m.Id == _selectedMutationId);
        if (mutation == null)
        {
            InfoResearchLabel.Text = "Unknown";
            return;
        }

        var isKnown = IsMutationKnown(mutation);

        if (!isKnown)
        {
            InfoResearchLabel.Text = "Unknown";
            return;
        }

        if (!IoCManager.Resolve<IPrototypeManager>().TryIndex<GeneticMutationPrototype>(_selectedMutationId, out var proto))
        {
            InfoResearchLabel.Text = "Unknown";
            return;
        }

        int total = proto.ResearchPoints;

        if (total <= 0)
        {
            InfoResearchLabel.Text = "0 / 0";
            return;
        }

        int completed = 0;

        if (ParentWindow is not null && ParentWindow.ResearchOriginal.TryGetValue(_selectedMutationId, out var original) && original > 0)
        {
            int remaining = ParentWindow.ResearchRemaining.TryGetValue(_selectedMutationId, out var rem)
                ? Math.Max(0, rem)
                : original;
            completed = original - remaining;
        }

        InfoResearchLabel.Text = completed >= total ? "Researched" : $"{completed} / {total}";
    }

    public void RefreshMutationIcons()
    {
        if (_currentMutations == null || _mutationButtons.Count != _currentMutations.Count)
            return;

        for (int i = 0; i < _mutationButtons.Count; i++)
        {
            var mut = _currentMutations[i];
            var button = (UniqueEnzymeButton)_mutationButtons[i];

            bool isDiscovered = ParentWindow?.DiscoveredMutationIds?.Contains(mut.Id) ?? false;
            bool isBase = ParentWindow?.BaseMutationIds?.Contains(mut.Id) ?? false;

            button.UpdateIcon(isDiscovered, isBase);

            if (mut.Enabled)
                button.Modulate = ActiveMutationTint;
            else
                button.Modulate = Color.White;
        }
    }

    private void ClearMutationDetails()
    {
        InfoNameLabel.Text = "";
        InfoDescLabel.Text = "";
        InfoInstabilityLabel.Text = "";
        InfoResearchLabel.Text = "";
    }

    private void UpdateRightPanelVisibilityAndButtons()
    {
        if (ParentWindow == null)
            return;

        var hasSelection = _selectedMutationId != null;
        InfoContainer.Visible = hasSelection;
        SequencerContainer.Visible = hasSelection;

        if (!hasSelection)
        {
            SaveMutationButton.Disabled = true;
            return;
        }

        UpdateResearchButtonState();
    }

    private void UpdatePrintSaveButtonState()
    {
        if (_selectedMutationId == null)
        {
            PrintActivatorButton.Disabled = true;
            PrintMutatorButton.Disabled = true;
            SaveMutationButton.Disabled = true;
            return;
        }

        bool isResearched = false;

        if (ParentWindow is not null && ParentWindow.ResearchOriginal.TryGetValue(_selectedMutationId, out var original))
        {
            if (original <= 0)
            {
                isResearched = true;
            }
            else
            {
                var remaining = ParentWindow.ResearchRemaining.TryGetValue(_selectedMutationId, out var rem)
                    ? Math.Max(0, rem)
                    : original;

                isResearched = remaining <= 0;
            }
        }

        PrintActivatorButton.Disabled = !isResearched;
        PrintMutatorButton.Disabled = !isResearched;

        var mutation = ParentWindow?.CurrentMutations?.Find(m => m.Id == _selectedMutationId);
        bool isSequenceComplete = mutation?.RevealedSequence == mutation?.OriginalSequence;
        bool isAlreadySaved = ParentWindow?.SavedMutations.Any(m => m.Id == _selectedMutationId) ?? false;

        SaveMutationButton.Disabled = !isSequenceComplete || isAlreadySaved;
    }

    private void UpdateResearchButtonState()
    {
        if (_selectedMutationId == null)
        {
            ResearchMutationButton.Disabled = true;
            return;
        }

        bool isInStorage = ParentWindow?.SavedMutations.Any(m => m.Id == _selectedMutationId) ?? false;
        if (!isInStorage)
        {
            ResearchMutationButton.Disabled = true;
            return;
        }

        if (ParentWindow == null || !ParentWindow.ResearchOriginal.TryGetValue(_selectedMutationId, out var original) || original <= 0)
        {
            ResearchMutationButton.Disabled = true;
            return;
        }

        var remaining = ParentWindow.ResearchRemaining.TryGetValue(_selectedMutationId, out var rem)
            ? Math.Max(0, rem)
            : original;

        if (remaining <= 0)
        {
            ResearchMutationButton.Disabled = true;
            return;
        }

        ResearchMutationButton.Disabled = false;

        var isActive = ParentWindow.ActiveResearchIds.Contains(_selectedMutationId);
        var newText = isActive
            ? Loc.GetString("dna-scanner-cancel-research")
            : Loc.GetString("dna-scanner-research-mutation");

        if (ResearchMutationButton.Text != newText)
            ResearchMutationButton.Text = newText;
    }

    public void ClearSelection()
    {
        if (_currentlyPressedButton != null)
            _currentlyPressedButton.Pressed = false;

        _currentlyPressedButton = null;
        _selectedMutationId = null;

        ClearMutationDetails();
        UpdateSequencerButtonsState();
        UpdateRightPanelVisibilityAndButtons();
        UpdatePrintSaveButtonState();
    }

    public void SetSelectedMutation(string? id, bool isStored)
    {
        UpdateSequencerButtonsState();
    }

    public void OnMutationSelected(string? id, bool isStored)
    {
        _selectedMutationId = id;
        _isSelectedMutationStored = isStored;

        if (string.IsNullOrEmpty(id))
        {
            ClearSelection();
            return;
        }

        var mutation = _currentMutations?.FirstOrDefault(m => m.Id == id);

        if (mutation == null)
            return;

        UpdateMutationDetails(mutation);
        LoadMutationSequence(mutation.RevealedSequence);
        UpdatePrintSaveButtonState();
        UpdateSequencerButtonsState();
        UpdateRightPanelVisibilityAndButtons();
        UpdateResearchButtonState();

        int selectedIndex = _currentMutations?.FindIndex(m => m.Id == id) ?? -1;

        if (selectedIndex >= 0 && selectedIndex < _mutationButtons.Count)
        {
            var button = _mutationButtons[selectedIndex];

            if (_currentlyPressedButton != null)
                _currentlyPressedButton.Pressed = false;

            button.Pressed = true;
            _currentlyPressedButton = button;
        }
    }

    private bool IsMutationKnown(MutationEntry mutation)
    {
        // Primary: server-confirmed discovery
        var isDiscovered = ParentWindow?.DiscoveredMutationIds?.Contains(mutation.Id) ?? false;

        // Fallback: sequence is fully revealed
        var isFullyRevealed = mutation.RevealedSequence == mutation.OriginalSequence;

        return isDiscovered || isFullyRevealed;
    }
}
