// SPDX-FileCopyrightText: 2026 Steve <marlumpy@gmail.com>
// SPDX-FileCopyrightText: 2026 marc-pelletier <113944176+marc-pelletier@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Genetics;
using Content.Shared._Funkystation.Genetics.Components;
using Content.Shared._Funkystation.Genetics.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Funkystation.Genetics.DnaScannerConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticistsConsoleStorageView : Control
{
    // Local fields for this view
    private readonly List<Button> _savedMutationButtons = new();
    private List<MutationEntry> _savedMutations = new();

    // Selection state (set by parent window)
    public GeneticistsConsoleWindow? ParentWindow { get; set; }
    private string? _selectedMutationId;

    // Events raised to parent / server
    public event Action<string>? OnDeleteMutationPressed;
    public event Action<string>? OnPrintActivatorPressed;
    public event Action<string>? OnPrintMutatorPressed;
    public event Action<string>? OnToggleResearchPressed;

    public GeneticistsConsoleStorageView()
    {
        RobustXamlLoader.Load(this);

        DeleteMutationButton.OnPressed += _ =>
        {
            if (_selectedMutationId != null)
                OnDeleteMutationPressed?.Invoke(_selectedMutationId);
        };

        StoragePrintActivatorButton.OnPressed += _ =>
        {
            if (_selectedMutationId != null)
                OnPrintActivatorPressed?.Invoke(_selectedMutationId);
        };

        StoragePrintMutatorButton.OnPressed += _ =>
        {
            if (_selectedMutationId != null)
                OnPrintMutatorPressed?.Invoke(_selectedMutationId);
        };

        StorageResearchMutationButton.OnPressed += _ =>
        {
            if (_selectedMutationId != null)
                OnToggleResearchPressed?.Invoke(_selectedMutationId);
        };
    }

    public void UpdateSavedMutations(List<MutationEntry> savedMutations)
    {
        ResearchingContainer.RemoveAllChildren();
        UnresearchedContainer.RemoveAllChildren();
        ResearchedContainer.RemoveAllChildren();

        _savedMutationButtons.Clear();
        _savedMutations = savedMutations;

        NoSavedSequencesLabel.Visible = savedMutations.Count == 0;
        StoredSequencesContainer.Visible = savedMutations.Count > 0;

        if (savedMutations.Count == 0)
            return;

        foreach (var mut in savedMutations)
        {
            var button = new Button
            {
                Text = mut.Name,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
                StyleClasses = { "ButtonSmall", "ButtonSquare" }
            };

            button.OnPressed += _ =>
            {
                // Deselect all previous
                foreach (var btn in _savedMutationButtons)
                    btn.Pressed = false;

                button.Pressed = true;

                _selectedMutationId = mut.Id;

                UpdateMutationDetails(mut);
                UpdateActionButtonsState();
            };

            _savedMutationButtons.Add(button);

            BoxContainer targetContainer;

            if (ParentWindow is not null && ParentWindow.ResearchOriginal.TryGetValue(mut.Id, out var original) && original > 0)
            {
                var remaining = ParentWindow.ResearchRemaining.TryGetValue(mut.Id, out var rem) ? rem : original;

                if (remaining <= 0)
                    targetContainer = ResearchedContainer;
                else if (ParentWindow.ActiveResearchIds.Contains(mut.Id))
                    targetContainer = ResearchingContainer;
                else
                    targetContainer = UnresearchedContainer;
            }
            else
            {
                targetContainer = UnresearchedContainer;
            }

            targetContainer.AddChild(button);
        }

        ResearchingCollapsible.Visible = ResearchingContainer.ChildCount > 0;
        UnresearchedCollapsible.Visible = UnresearchedContainer.ChildCount > 0;
        ResearchedCollapsible.Visible = ResearchedContainer.ChildCount > 0;
        UpdateResearchCountLabel();
    }

    public void OnMutationSelected(string? id)
    {
        if (string.IsNullOrEmpty(id))
        {
            ClearSelection();
            return;
        }

        _selectedMutationId = id;

        var mutation = _savedMutations.FirstOrDefault(m => m.Id == id);
        if (mutation != null)
        {
            UpdateMutationDetails(mutation);
        }

        UpdateActionButtonsState();
    }

    private void UpdateMutationDetails(MutationEntry mutation)
    {
        var isKnown = IsMutationKnown(mutation);

        string displayName = isKnown ? mutation.Name : $"Mutation {mutation.Block:00}";

        StorageInfoNameLabel.Text = displayName;

        StorageInfoDescLabel.Text = isKnown
            ? (mutation.Description ?? "No description.")
            : "Undiscovered mutation.";

        StorageInfoInstabilityLabel.Text = isKnown
            ? mutation.Instability.ToString()
            : "Unknown";

        UpdateConflictsDisplay(mutation);
        RefreshResearchLabel();
    }

    private void UpdateConflictsDisplay(MutationEntry mutation)
    {
        var isKnown = IsMutationKnown(mutation);

        if (!isKnown || mutation.Conflicts is not { Count: > 0 } conflicts || ParentWindow?.DiscoveredMutationIds is null)
        {
            StorageConflictsLabelContainer.Visible = false;
            return;
        }

        var knownNames = new List<string>();

        foreach (var conflictId in conflicts)
        {
            // Keep conflicts gated behind real discovery
            if (!ParentWindow.DiscoveredMutationIds.Contains(conflictId))
                continue;

            if (IoCManager.Resolve<IPrototypeManager>()
                .TryIndex<GeneticMutationPrototype>(conflictId, out var proto))
            {
                knownNames.Add(proto.Name);
            }
        }

        if (knownNames.Count == 0)
        {
            StorageConflictsLabelContainer.Visible = false;
            return;
        }

        knownNames.Sort();
        StorageConflictsLabel.Text = string.Join(", ", knownNames);
        StorageConflictsLabelContainer.Visible = true;
    }

    public void RefreshResearchLabel()
    {
        if (string.IsNullOrEmpty(_selectedMutationId))
        {
            StorageInfoResearchLabel.Text = "";
            return;
        }

        // Get the mutation from saved list
        var mutation = _savedMutations.FirstOrDefault(m => m.Id == _selectedMutationId);
        if (mutation == null)
        {
            StorageInfoResearchLabel.Text = "Unknown";
            return;
        }

        var isKnown = IsMutationKnown(mutation);

        if (!isKnown)
        {
            StorageInfoResearchLabel.Text = "Unknown";
            return;
        }

        if (!IoCManager.Resolve<IPrototypeManager>().TryIndex<GeneticMutationPrototype>(_selectedMutationId, out var proto))
        {
            StorageInfoResearchLabel.Text = "Unknown";
            return;
        }

        int total = proto.ResearchPoints;

        if (total <= 0)
        {
            StorageInfoResearchLabel.Text = "0 / 0";
            return;
        }

        int completed = 0;

        if (ParentWindow is not null && ParentWindow.ResearchOriginal.TryGetValue(_selectedMutationId, out var original) && original > 0)
        {
            int remaining = ParentWindow.ResearchRemaining.TryGetValue(_selectedMutationId, out var rem)
                ? Math.Max(0, rem)
                : original;
            completed = original - remaining;
        }

        StorageInfoResearchLabel.Text = completed >= total ? "Researched" : $"{completed} / {total}";
    }

    private void UpdateActionButtonsState()
    {
        var hasSelection = !string.IsNullOrEmpty(_selectedMutationId);

        if (!hasSelection)
        {
            StoragePrintActivatorButton.Disabled = true;
            StoragePrintMutatorButton.Disabled = true;
            DeleteMutationButton.Disabled = true;
            StorageResearchMutationButton.Disabled = true;
            return;
        }

        bool isResearched = false;
        if (ParentWindow is not null && ParentWindow.ResearchOriginal.TryGetValue(_selectedMutationId!, out var original))
        {
            if (original <= 0)
                isResearched = true;
            else
            {
                var remaining = ParentWindow.ResearchRemaining.TryGetValue(_selectedMutationId!, out var rem)
                    ? Math.Max(0, rem)
                    : original;
                isResearched = remaining <= 0;
            }
        }

        StoragePrintActivatorButton.Disabled = !isResearched;
        StoragePrintMutatorButton.Disabled = !isResearched;
        DeleteMutationButton.Disabled = false; // always enabled if selected in storage

        // Research button only for stored mutations with research points left
        bool showResearch = false;
        string researchText = Loc.GetString("dna-scanner-research-mutation");

        if (ParentWindow is not null && ParentWindow.ResearchOriginal.TryGetValue(_selectedMutationId!, out var orig) && orig > 0)
        {
            var rem = ParentWindow.ResearchRemaining.TryGetValue(_selectedMutationId!, out var r) ? Math.Max(0, r) : orig;
            if (rem > 0)
            {
                showResearch = true;
                if (ParentWindow.ActiveResearchIds.Contains(_selectedMutationId!))
                    researchText = Loc.GetString("dna-scanner-cancel-research");
            }
        }

        StorageResearchMutationButton.Disabled = !showResearch;
        StorageResearchMutationButton.Text = researchText;
    }

    private void UpdateResearchCountLabel()
    {
        if (ParentWindow == null)
            return;

        int current = ParentWindow.ActiveResearchIds.Count;
        ResearchCountLabel.Text = $"{current}/5";
    }

    public void UpdateDiscoveredMutations(HashSet<string>? discoveredIds)
    {
        if (ParentWindow == null)
            return;

        ParentWindow.DiscoveredMutationIds = discoveredIds;
        if (!string.IsNullOrEmpty(_selectedMutationId))
        {
            var mut = _savedMutations.FirstOrDefault(m => m.Id == _selectedMutationId);
            if (mut != null)
                UpdateMutationDetails(mut);
        }
    }

    public void UpdateResearchData(Dictionary<string, int> remaining, Dictionary<string, int> original, HashSet<string> activeIds)
    {
        if (ParentWindow == null)
            return;

        ParentWindow.ResearchRemaining = remaining;
        ParentWindow.ResearchOriginal = original;
        ParentWindow.ActiveResearchIds = activeIds;

        UpdateResearchCountLabel();
        UpdateActionButtonsState();

        if (!string.IsNullOrEmpty(_selectedMutationId))
        {
            var mut = _savedMutations.FirstOrDefault(m => m.Id == _selectedMutationId);
            if (mut != null)
                UpdateMutationDetails(mut);
        }
    }

    public void ClearSelection()
    {
        foreach (var btn in _savedMutationButtons)
            btn.Pressed = false;

        _selectedMutationId = null;
        ClearMutationDetails();
        UpdateActionButtonsState();
    }

    private void ClearMutationDetails()
    {
        StorageInfoNameLabel.Text = "";
        StorageInfoDescLabel.Text = "";
        StorageInfoInstabilityLabel.Text = "";
        StorageInfoResearchLabel.Text = "";
        StorageConflictsLabelContainer.Visible = false;
    }

    private bool IsMutationKnown(MutationEntry mutation)
    {
        // Primary: server-confirmed discovery
        var isDiscovered = ParentWindow?.DiscoveredMutationIds?.Contains(mutation.Id) ?? false;

        // Fallback: sequence is fully revealed
        var isFullyRevealed = mutation.RevealedSequence == mutation.OriginalSequence;

        return isDiscovered || isFullyRevealed;
    }
}
