// SPDX-FileCopyrightText: 2026 Steve <marlumpy@gmail.com>
// SPDX-FileCopyrightText: 2026 marc-pelletier <113944176+marc-pelletier@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Genetics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Funkystation.Genetics.GeneticistsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticistsConsoleWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private GeneticistsConsoleUniqueEnzymesView _enzymesView = null!;
    private GeneticistsConsoleStorageView _storageView = null!;

    private Control _activeView = null!;

    // Shared data
    internal List<MutationEntry>? CurrentMutations;
    internal List<MutationEntry> SavedMutations = new();
    internal HashSet<string>? DiscoveredMutationIds;
    internal Dictionary<string, int> ResearchRemaining = new();
    internal Dictionary<string, int> ResearchOriginal = new();
    internal HashSet<string> ActiveResearchIds = new();
    internal HashSet<string> BaseMutationIds { get; private set; } = new();
    internal bool IsSubjectDead;

    // Events that go to server
    public event Action<int, char, string>? OnSequencerButtonPressed;
    public event Action<string>? OnSaveMutationPressed;
    public event Action<string>? OnDeleteMutationPressed;
    public event Action<string>? OnPrintActivatorPressed;
    public event Action<string>? OnPrintMutatorPressed;
    public event Action? OnScrambleDnaPressed;
    public event Action<string>? OnToggleResearchPressed;
    public event Action? OnJokerUsed;
    public event Action<string, bool>? OnMutationSelectionChanged;

    public GeneticistsConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        // Shared top buttons
        ScrambleDnaButton.OnPressed += _ => OnScrambleDnaPressed?.Invoke();

        _enzymesView = new GeneticistsConsoleUniqueEnzymesView();
        _storageView = new GeneticistsConsoleStorageView();

        ViewContainer.AddChild(_enzymesView);
        ViewContainer.AddChild(_storageView);
        _enzymesView.ParentWindow = this;
        _storageView.ParentWindow = this;

        _activeView = _enzymesView;
        _storageView.Visible = false;

        // Tab buttons
        UniqueEnzymesTabButton.OnPressed += _ => SwitchToEnzymes();
        StorageTabButton.OnPressed += _ => SwitchToStorage();

        // Forward view events to server
        _enzymesView.OnSequencerButtonPressed += (i, c, id) => OnSequencerButtonPressed?.Invoke(i, c, id);
        _enzymesView.OnSaveMutationPressed += id => OnSaveMutationPressed?.Invoke(id);
        _storageView.OnDeleteMutationPressed += id => OnDeleteMutationPressed?.Invoke(id);
        _enzymesView.OnPrintActivatorPressed += id => OnPrintActivatorPressed?.Invoke(id);
        _storageView.OnPrintActivatorPressed += id => OnPrintActivatorPressed?.Invoke(id);
        _enzymesView.OnPrintMutatorPressed += id => OnPrintMutatorPressed?.Invoke(id);
        _storageView.OnPrintMutatorPressed += id => OnPrintMutatorPressed?.Invoke(id);
        _enzymesView.OnToggleResearchPressed += id => OnToggleResearchPressed?.Invoke(id);
        _storageView.OnToggleResearchPressed += id => OnToggleResearchPressed?.Invoke(id);
        _enzymesView.OnJokerUsed += () => OnJokerUsed?.Invoke();

        SwitchToEnzymes();
    }

    private void SwitchToEnzymes()
    {
        _activeView.Visible = false;
        _enzymesView.Visible = true;
        _activeView = _enzymesView;

        UniqueEnzymesTabButton.Pressed = true;
        StorageTabButton.Pressed = false;
    }

    private void SwitchToStorage()
    {
        _activeView.Visible = false;
        _storageView.Visible = true;
        _activeView = _storageView;

        UniqueEnzymesTabButton.Pressed = false;
        StorageTabButton.Pressed = true;
    }

    public void UpdateSubjectInfo(string? name, string? health, float? radiationDamage, int instability, TimeSpan? scrambleCooldownEnd)
    {
        var hasSubject = name != null;
        SubjectNameLabel.Text = hasSubject ? name : "";
        SubjectInfoBox.Visible = hasSubject;

        HealthLabel.Text = health ?? "--";
        RadiationDamageLabel.Text = radiationDamage?.ToString() ?? "--";
        GeneticInstabilityLabel.Text = instability.ToString();

        bool isNowDead = health == "Dead";
        bool justDied = !IsSubjectDead && isNowDead;

        IsSubjectDead = isNowDead;

        if (justDied)
            _enzymesView.UpdateSequencerButtonsState();

        UpdateScrambleButtonState(scrambleCooldownEnd);

        if (!hasSubject)
        {
            _enzymesView.ClearSelection();
            UpdateGeneticsTab(null, null);
        }
    }

    private void UpdateScrambleButtonState(TimeSpan? cooldownEnd)
    {
        var hasSubject = SubjectInfoBox.Visible; // TODO: Not this

        if (!cooldownEnd.HasValue || cooldownEnd.Value <= _timing.CurTime)
        {
            ScrambleDnaButton.Disabled = !hasSubject;
            ScrambleDnaButton.Text = Loc.GetString("dna-scanner-scramble-dna");
            return;
        }

        var remaining = cooldownEnd.Value - _timing.CurTime;
        ScrambleDnaButton.Disabled = true;
        ScrambleDnaButton.Text = Loc.GetString("dna-scanner-scramble-cooldown",
            ("seconds", (int)remaining.TotalSeconds));
    }

    public void UpdateGeneticsTab(List<MutationEntry>? mutations, HashSet<string>? baseMutationIds)
    {
        CurrentMutations = mutations;
        BaseMutationIds = baseMutationIds ?? new HashSet<string>();
        _enzymesView.UpdateGeneticsTab(mutations, baseMutationIds);
    }

    public void UpdateSavedMutations(List<MutationEntry> savedMutations)
    {
        SavedMutations = savedMutations;
        _storageView.UpdateSavedMutations(savedMutations);
    }

    public void UpdateDiscoveredMutations(HashSet<string> discoveredIds)
    {
        DiscoveredMutationIds = discoveredIds;
        _enzymesView.UpdateDiscoveredMutations(discoveredIds);
        _storageView.UpdateDiscoveredMutations(discoveredIds);
    }

    public void UpdateResearchData(Dictionary<string, int> remaining, Dictionary<string, int> original, HashSet<string> activeIds)
    {
        ResearchRemaining = remaining;
        ResearchOriginal = original;
        ActiveResearchIds = activeIds;

        _enzymesView.UpdateResearchData(remaining, original, activeIds);
        _storageView.UpdateResearchData(remaining, original, activeIds);
    }

    public void UpdateResearchLabel()
    {
        _enzymesView.RefreshResearchLabel();
        _storageView.RefreshResearchLabel();
    }

    public void UpdateJokerCooldown(TimeSpan? cooldownEnd)
    {
        _enzymesView.UpdateJokerButtonState(cooldownEnd);
    }
}
