- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Bagel
  - Box
  - Cluster
  #- Cog # Goobstation - cog is broken
  - Core
 #- Divide #funkystation
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Train
  - FlandHighPop
  - OasisHighPop
  - Barratry # Goobstation - Re-add barratry
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
