- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber 
  - Atlas 
  - Bagel 
  - Box   
  - Cluster 
  #- Cog # Goobstation - cog is broken  
  - Core  
  - Fland  
  - Marathon 
  - Meta 
  - Oasis 
  - Omega 
  - Origin 
  - Saltern 
  - Packed 
  - Reach
  - Train 
  - FlandHighPop
  - OasisHighPop
  #- Barratry # Goobstation - Re-add barratry - Funkystation - Barratrauma
  - Kettle 
