# SPDX-FileCopyrightText: 2025 empty0set <16693552+empty0set@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 empty0set <empty0set@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: PartyMaker
  name: job-name-party-maker
  description: job-name-party-maker
  playTimeTracker: JobPartyMaker
  startingGear: PartyMakerGear
  icon: "JobIconPartyMaker"
  supervisors: job-supervisors-hop
  setPreference: false
  access:
  - Service
  - Maintenance
  - Theatre

- type: startingGear
  id: PartyMakerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHawaiBlack
    id: PartyMakerPDA
    ears: ClothingHeadsetService
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesColorBlack
  storage:
    back:
    - SuperSynthesizerInstrument
