using System.Linq;
using Content.Client._CD.Records.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Medical.MedicalRecords;
using Content.Shared._Funkystation.Records;
using Content.Shared.Security;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Funkystation.Medical.MedicalRecordsConsole.UI;


[GenerateTypedNameReferences]
public sealed partial class MedicalRecordsMenu : FancyWindow
{
    public struct CharacterListMetadata
    {
        public uint CharacterRecordKey;
        public uint? StationRecordKey;
    }

    public static readonly Color BackgroundColor = Color.FromHex("#25252a"); // Dark grey
    public static readonly Color ContentPanelColor = Color.FromHex("#1a1a1a"); // Darker grey for content areas
    public static readonly Color BorderColor = Color.FromHex("#404040"); // Light grey border
    public static readonly Color ErrorColor = Color.FromHex("#ff0000"); // Red for validation errors

    public event Action<CharacterListMetadata?>? OnListingItemSelected;
    public event Action<StationRecordFilterType, string?>? OnFiltersChanged;

    private bool _isPopulating;
    private StationRecordFilterType _filterType;

    /// <summary>
    /// The key to the record of the currently selected item in the listing.
    /// </summary>
    private uint? _selectedListingKey;

    /// <summary>
    /// The key to the record that is currently visible.
    /// </summary>
    /// <remarks>
    /// This may differ from <see cref="_selectedListingKey"/> because this contents has not been updated yet to reflect the new selection.
    /// </remarks>
    private uint? _openRecordKey;


    public MedicalRecordsMenu()
    {
        RobustXamlLoader.Load(this);

        // There is no reason why we can't just steal the StationRecordFilter class.
        // If wizden adds a new kind of filtering we want to replicate it here.
        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            RecordFilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        CharacterListing.OnItemSelected += _ =>
        {
            if (!CharacterListing.GetSelected().Any())
                return;
            var selected = CharacterListing.GetSelected().First();
            var meta = (CharacterListMetadata)selected.Metadata!;
            _selectedListingKey = meta.CharacterRecordKey;
            if (!_isPopulating)
                OnListingItemSelected?.Invoke(meta);
        };

        CharacterListing.OnItemDeselected += _ =>
        {
            // When we populate the records, we clear the contents of the listing.
            // This could cause a deselection but we don't want to really deselect because it would
            // interrupt what the player is doing.
            if (!_isPopulating)
                OnListingItemSelected?.Invoke(null);
            _selectedListingKey = null;
        };

        RecordFilterSearch.OnPressed += _ =>
        {
            OnFiltersChanged?.Invoke(_filterType, RecordFiltersValue.Text);
        };

        RecordFilterReset.OnPressed += _ =>
        {
            OnFiltersChanged?.Invoke(StationRecordFilterType.Name, null);
            RecordFiltersValue.Clear();
        };

        RecordFiltersValue.OnTextEntered += text =>
        {
            OnFiltersChanged?.Invoke(_filterType, text.Text);
        };

        RecordFilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;
            _filterType = type;
            RecordFilterType.SelectId(eventArgs.Id);
        };
    }

    // If we are using wizden's class we might as well use their localization.
    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }

    /// <summary>
    /// Select the record in the listing for the given key.
    /// </summary>
    /// <param name="key">The index of the record in the dictionary</param>
    private void SelectRecordKey(uint? key)
    {
        if (_selectedListingKey == key)
            return;
        _selectedListingKey = key;

        _isPopulating = true;

        CharacterListing.ClearSelected();

        // I wish there was a better way of doing this
        if (key != null)
        {
            foreach (var item in CharacterListing)
            {
                if (((CharacterListMetadata) item.Metadata!).CharacterRecordKey == key)
                {
                    item.Selected = true;
                    break;
                }
            }
        }

        _isPopulating = false;
    }

    private bool CharacterListNeedsRepopulating(IReadOnlyDictionary<uint, MedicalRecordsConsoleState.CharacterInfo> newKeys)
    {
        var newCount = newKeys.Count;
        if (newCount != CharacterListing.Count)
            return true;

        // Given that there is the same number of keys in the dictionary as in items in the listing, they are not equal
        // if and only if there exists a key in the listing that is not in the dictionary
        foreach (var item in CharacterListing)
        {
            var key = ((CharacterListMetadata)item.Metadata!).CharacterRecordKey;
            if (!newKeys.ContainsKey(key))
            {
                return true;
            }
        }

        return false;
    }

    public void UpdateState(MedicalRecordsConsoleState state)
    {
        #region Visibility

        // Disable listing if we don't have one selected
        if (state.CharacterList == null)
        {
            CharacterListingStatus.Visible = true;
            CharacterListing.Visible = false;
            CharacterListingStatus.Text = Loc.GetString("cd-record-viewer-empty-state");
            return;
        }

        CharacterListingStatus.Visible = false;
        CharacterListing.Visible = true;

        #endregion

        #region PopulateListing

        if (state.Filter != null)
        {
            RecordFiltersValue.SetText(state.Filter.Value);
            RecordFilterType.SelectId((int) state.Filter.Type);
        }

        if (CharacterListNeedsRepopulating(state.CharacterList))
        {
            _isPopulating = true;

            CharacterListing.Clear();

            // Add the records to the listing in a sorted order. There is probably are faster way of doing this, but
            // this is not really a hot code path.
            state.CharacterList
                // The items in this tuple are as follows: (name of character, CharacterListMetadata)
                .Select(r
                    => (CharacterName: r.Value.CharacterDisplayName, new CharacterListMetadata() { CharacterRecordKey = r.Key, StationRecordKey = r.Value.StationRecordKey}))
                .OrderBy(r => r.Item1)
                .ToList()
                .ForEach(r => CharacterListing.AddItem(r.Item1, metadata: r.Item2));

            _isPopulating = false;
        }

        SelectRecordKey(state.SelectedIndex);

        #endregion

        #region FillRecordContainer

        // Enable container if we have a record selected
        if (state.SelectedRecord == null)
        {
            RecordContainerStatus.Visible = true;
            RecordContainer.Visible = false;
            return;
        }

        RecordContainerStatus.Visible = false;
        RecordContainer.Visible = true;

        // Do not needlessly reload the record if not needed. This is mainly done to prevent a bug in the admin record viewer.
        if (state.SelectedIndex == _openRecordKey)
            return;
        _openRecordKey = state.SelectedIndex;

        var record = state.SelectedRecord!;
        var cr = record.PRecords;

        // Basic info -- clean up these box names
        CrewmateName.Text = record.Name;
        AgeText.Text = record.Age.ToString();
        JobText.Text = record.JobTitle; /* At some point in the future we might want to display the icon */
        GenderText.Text = record.Gender.ToString();
        SpeciesText.Text = record.Species;
        HeightText.Text = cr.Height + " " + UnitConversion.GetImperialDisplayLength(cr.Height);
        WeightText.Text = cr.Weight + " " + UnitConversion.GetImperialDisplayMass(cr.Weight);

        #endregion

    }
}
