// SPDX-FileCopyrightText: 2025 rex1431ify <r.l@live.se>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.Graphics;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class WordleUiFragment : BoxContainer
{
    public event Action<char>? OnLetterPressed;
    public event Action? OnBackspacePressed;
    public event Action? OnSubmitPressed;
    public event Action? OnNewGamePressed;

    private Label? _currentGuessLabel;
    private Label? _statusLabel;
    private BoxContainer? _gameBoardContainer;
    private BoxContainer? _keyboardContainer;
    private Button? _newGameButton;
    private Button? _backspaceButton;
    private Button? _submitButton;

    private readonly List<List<PanelContainer>> _guessTiles = new();
    private readonly Dictionary<char, Button> _keyboardButtons = new();

    // Wordle colors
    private const string CorrectColor = "#6aaa64"; // Green
    private const string WrongSpotColor = "#c9b458"; // Yellow
    private const string NotInWordColor = "#3a3a3c"; // Gray
    private const string DefaultColor = "#565758"; // Dark gray

    public WordleUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _currentGuessLabel = CurrentGuessLabel;
        _statusLabel = StatusLabel;
        _gameBoardContainer = GameBoardContainer;
        _keyboardContainer = KeyboardContainer;
        _newGameButton = NewGameButton;
        _backspaceButton = BackspaceButton;
        _submitButton = SubmitButton;

        if (_newGameButton != null)
            _newGameButton.OnPressed += _ => OnNewGamePressed?.Invoke();

        if (_backspaceButton != null)
            _backspaceButton.OnPressed += _ => OnBackspacePressed?.Invoke();

        if (_submitButton != null)
            _submitButton.OnPressed += _ => OnSubmitPressed?.Invoke();

        CreateGameBoard();
        CreateKeyboard();
    }

    private void CreateGameBoard()
    {
        if (_gameBoardContainer == null)
            return;

        _gameBoardContainer.RemoveAllChildren();
        _guessTiles.Clear();

        // Create 6 rows for 6 attempts
        for (int row = 0; row < 6; row++)
        {
            var rowContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = false,
                VerticalExpand = false,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(2),
                SeparationOverride = 2
            };
            var rowTiles = new List<PanelContainer>();

            // Create 5 letter tiles per row
            for (int col = 0; col < 5; col++)
            {
                var tilePanel = new PanelContainer
                {
                    HorizontalExpand = false,
                    VerticalExpand = false,
                    MinHeight = 38,
                    MinWidth = 38,
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.FromHex(DefaultColor),
                        BorderColor = Color.FromHex("#ffffff"),
                        BorderThickness = new Thickness(1)
                    }
                };

                var letterLabel = new Label
                {
                    Text = "",
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    FontColorOverride = Color.White,
                };

                tilePanel.AddChild(letterLabel);
                rowContainer.AddChild(tilePanel);
                rowTiles.Add(tilePanel);
            }

            _gameBoardContainer.AddChild(rowContainer);
            _guessTiles.Add(rowTiles);
        }
    }

    private void CreateKeyboard()
    {
        if (_keyboardContainer == null)
            return;

        _keyboardContainer.RemoveAllChildren();
        _keyboardButtons.Clear();

        // QWERTY layout
        var rows = new[]
        {
            "QWERTYUIOP",
            "ASDFGHJKL",
            "ZXCVBNM"
        };

        foreach (var row in rows)
        {
            var rowContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(2),
                SeparationOverride = 2
            };

            foreach (var letter in row)
            {
                var button = new Button
                {
                    Text = letter.ToString(),
                    HorizontalExpand = true,
                    MinHeight = 20,
                    MinWidth = 16
                };

                var charCopy = letter;
                button.OnPressed += _ => OnLetterPressed?.Invoke(charCopy);
                _keyboardButtons[charCopy] = button;
                rowContainer.AddChild(button);
            }

            _keyboardContainer.AddChild(rowContainer);
        }
    }

    public void UpdateState(WordleUiState state)
    {
        // Update current guess display
        if (_currentGuessLabel != null)
        {
            var display = state.CurrentGuess.PadRight(5, '_');
            _currentGuessLabel.Text = $"Current: {string.Join(" ", display.ToCharArray())}";
        }

        // Clear all tiles first
        for (int i = 0; i < _guessTiles.Count; i++)
        {
            for (int j = 0; j < _guessTiles[i].Count; j++)
            {
                var tilePanel = _guessTiles[i][j];
                if (tilePanel.Children.Count() > 0 && tilePanel.Children.FirstOrDefault() is Label label)
                {
                    label.Text = "";
                    label.FontColorOverride = Color.White;
                }
                tilePanel.PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex(DefaultColor),
                    BorderColor = Color.FromHex("#ffffff"),
                    BorderThickness = new Thickness(1)
                };
            }
        }

        // Reset keyboard to default color
        foreach (var button in _keyboardButtons.Values)
        {
            button.Disabled = false;
            button.Modulate = Color.White; // Reset color modulation
        }

        // Track best state for each letter (green > yellow > gray)
        var letterBestState = new Dictionary<char, int>();

        // Update game board with previous guesses
        for (int guessIdx = 0; guessIdx < state.PreviousGuesses.Count && guessIdx < _guessTiles.Count; guessIdx++)
        {
            var guess = state.PreviousGuesses[guessIdx];
            var letterStates = state.LetterStates[guessIdx];

            for (int letterIdx = 0; letterIdx < 5 && letterIdx < guess.Length; letterIdx++)
            {
                var letter = char.ToUpper(guess[letterIdx]);
                var tilePanel = _guessTiles[guessIdx][letterIdx];
                if (tilePanel.Children.Count() > 0 && tilePanel.Children.FirstOrDefault() is Label label)
                {
                    label.Text = letter.ToString();
                }

                // Set tile color based on letter state
                string tileColor = DefaultColor;
                int letterState = letterStates[letterIdx];
                switch (letterState)
                {
                    case 2: // Correct position (green)
                        tileColor = CorrectColor;
                        break;
                    case 1: // Wrong position (yellow)
                        tileColor = WrongSpotColor;
                        break;
                    case 3: // Not in word (gray)
                        tileColor = NotInWordColor;
                        break;
                    default:
                        tileColor = DefaultColor;
                        break;
                }

                tilePanel.PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex(tileColor),
                    BorderColor = Color.FromHex("#ffffff"),
                    BorderThickness = new Thickness(1)
                };

                // Track best state for this letter (prioritize: 2 > 1 > 3)
                if (!letterBestState.ContainsKey(letter) || letterState == 2 || (letterState == 1 && letterBestState[letter] != 2))
                {
                    letterBestState[letter] = letterState;
                }
            }
        }

        // Update keyboard button colors based on best letter states
        foreach (var kvp in letterBestState)
        {
            var letter = kvp.Key;
            var state_val = kvp.Value;

            if (_keyboardButtons.TryGetValue(letter, out var button))
            {
                string buttonColor = DefaultColor;
                switch (state_val)
                {
                    case 2: // Correct position (green)
                        buttonColor = CorrectColor;
                        break;
                    case 1: // Wrong position (yellow)
                        buttonColor = WrongSpotColor;
                        break;
                    case 3: // Not in word (gray)
                        buttonColor = NotInWordColor;
                        break;
                }

                // Apply color via modulation for visible feedback
                button.Modulate = Color.FromHex(buttonColor);
            }
        }

        // Update status
        if (_statusLabel != null)
        {
            if (state.GameWon)
                _statusLabel.Text = "🎉 You Won!";
            else if (state.GameLost)
                _statusLabel.Text = $"Game Over! Word: {state.SecretWord}";
            else
                _statusLabel.Text = $"Attempts: {state.AttemptsRemaining}";
        }

        // Disable/enable buttons based on game state
        if (_newGameButton != null)
            _newGameButton.Disabled = !(state.GameWon || state.GameLost);

        if (_backspaceButton != null)
            _backspaceButton.Disabled = state.GameWon || state.GameLost;

        if (_submitButton != null)
            _submitButton.Disabled = state.GameWon || state.GameLost || state.CurrentGuess.Length < 5;
    }
}
