using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Funkystation.Medical.Records.UI;

/// <summary>
/// For generating a new checklist entry for allergies, prescriptions, family history
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RecordChecklistEntry : BoxContainer
{
    public RecordChecklistEntry(string name, bool isChecked)
    {
        ItemLabel.Text = name;
        ItemCheckBox.Pressed = isChecked;
    }
}
