using System.Linq;
using System.Numerics;
using Content.Shared.Preferences;
using Content.Shared._CD.Records;
using Content.Client._CD.Records.UI;
using Content.Shared._Funkystation.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Medical.Records.UI;

/// <summary>
/// The record editor tab that gets "injected" into the character editor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RecordEditorGui : Control
{
    /// <summary>
    /// Delegate that tells the editor to save records when the save button is pressed
    /// </summary>
    private readonly Action<PlayerProvidedCharacterRecords> _updateProfileRecords;

    private readonly IPrototypeManager _prototypeManager;
    private PlayerProvidedCharacterRecords _records = default!;
    private readonly ISawmill _sawmill = default!;

    public RecordEditorGui(Action<PlayerProvidedCharacterRecords> updateProfileRecords, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _updateProfileRecords = updateProfileRecords;
        _prototypeManager = prototypeManager;

        #region initialization

        // add options to each dropdown depending on the enums
        foreach (var insuranceProvider in Enum.GetValues<InsuranceProviders>())
        {
            AddInsuranceProvider(insuranceProvider);
        }

        foreach (var insurancetype in Enum.GetValues<InsuranceTypes>())
        {
            AddInsuranceType(insurancetype);
        }

        foreach (var bloodtype in Enum.GetValues<BloodTypes>())
        {
            AddBloodType(bloodtype);
        }

        #endregion

        #region GeneralInformation

        HeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newHeight))
                return;
            UpdateImperialHeight(newHeight);
            UpdateRecords(_records.WithHeight(newHeight));
        };

        WeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newWeight))
                return;
            UpdateImperialWeight(newWeight);
            UpdateRecords(_records.WithWeight(newWeight));
        };

        IdentifyingFeaturesEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithIdentifyingFeatures(args.Text));
        };

        WorkAuthCheckBox.OnToggled += args =>
        {
            UpdateRecords(_records.WithWorkAuth(args.Pressed));
        };

        InsuranceCheckBox.OnToggled += args =>
        {
            UpdateRecords(_records.WithInsurance(args.Pressed));
        };

        InsuranceCompanyDropdown.OnItemSelected += args =>
        {
            UpdateRecords(_records.WithInsuranceProvider(args.Id));
        };

        InsurancePlanDropdown.OnItemSelected += args =>
        {
            UpdateRecords(_records.WithInsuranceType(args.Id));
        };

        #endregion

        #region MedicalInformation

        BloodTypeDropdown.OnItemSelected += args =>
        {
            UpdateRecords(_records.WithBloodType(args.Id));
        };

        PostmortemEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithPostmortemInstructions(args.Text));
        };

        #endregion
    }

    public void Update(HumanoidCharacterProfile? profile)
    {
        _records = profile?.CDCharacterRecords ?? PlayerProvidedCharacterRecords.DefaultRecords();
        UpdateWidgets();
    }

    private void UpdateRecords(PlayerProvidedCharacterRecords records)
    {
        records.EnsureValid();
        _records = records;
        _updateProfileRecords(_records);
        UpdateWidgets();
    }

    private void UpdateWidgets()
    {
        // general information
        HeightEdit.SetText(_records.Height.ToString());
        UpdateImperialHeight(_records.Height);
        WeightEdit.SetText(_records.Weight.ToString());
        UpdateImperialWeight(_records.Weight);

        IdentifyingFeaturesEdit.SetText(_records.IdentifyingFeatures);

        WorkAuthCheckBox.Pressed = _records.HasWorkAuthorization;

        InsuranceCheckBox.Pressed = _records.HasInsurance;

        // this feels nasty
        if (_records.HasInsurance == false)
        {
            InsuranceCompanyDropdown.SelectId(0);
            InsuranceCompanyDropdown.Disabled = true;

            InsurancePlanDropdown.SelectId(0);
            InsurancePlanDropdown.Disabled = true;
        }
        else
        {
            InsuranceCompanyDropdown.Disabled = false;
            InsuranceCompanyDropdown.SelectId(_records.InsuranceProvider);

            InsurancePlanDropdown.Disabled = false;
            InsurancePlanDropdown.SelectId(_records.InsuranceType);
        }

        // medical information

        BloodTypeDropdown.SelectId(_records.BloodType);
        PostmortemEdit.SetText(_records.PostmortemInstructions);

        RefreshMedicalInformation();
    }

    /* height/weight updating and conversion */
    private void UpdateImperialHeight(int newHeight)
    {
        HeightImperialLabel.Text = UnitConversion.GetImperialDisplayLength(newHeight);
    }

    private void UpdateImperialWeight(int newWeight)
    {
        WeightImperialLabel.Text = UnitConversion.GetImperialDisplayMass(newWeight);
    }

    /* insurance dropdowns */
    private void AddInsuranceProvider(InsuranceProviders provider)
    {
        var name = Loc.GetString($"character-records-insurance-provider-{provider.ToString().ToLower()}");
        InsuranceCompanyDropdown.AddItem(name, (int)provider);
    }

    private void AddInsuranceType(InsuranceTypes type)
    {
        var name = Loc.GetString($"character-records-insurance-type-{type.ToString().ToLower()}");
        InsurancePlanDropdown.AddItem(name, (int)type);
    }

    /* blood type dropdown */
    private void AddBloodType(BloodTypes type)
    {
        var name = Loc.GetString($"character-records-blood-{type.ToString().ToLower()}");
        BloodTypeDropdown.AddItem(name, (int)type);
    }

    /// <summary>
    /// Generates/refreshes the "Medical Info" checkboxes based on the given <see cref="MedicalInfoPrototype"/>
    /// </summary>
    private void RefreshMedicalInformation()
    {
        MedicalInfoContainer.DisposeAllChildren();

        var info = _prototypeManager.EnumeratePrototypes<MedicalInfoPrototype>()
            .OrderBy(t => Loc.GetString(t.Name))
            .ToList();

        // if there's no prototypes, generate a default label with no info
        if (info.Count < 1)
        {
            MedicalInfoContainer.AddChild(new Label
            {
                Text = Loc.GetString("humanoid-profile-editor-no-traits"),
                FontColorOverride = Color.Gray,
            });
            return;
        }

        Dictionary<string, List<string>> infoGroups = new();

        foreach (var entry in info)
        {
            if (entry.Category == null)
            {
                _sawmill.Warning($"Medical Info prototype {entry.ID} is missing a category and will be skipped.");
                continue;
            }

            var group = infoGroups.GetOrNew(entry.Category);
            group.Add(entry.ID);
        }

        // setup ui
        foreach (var (categoryId, categoryInfo) in infoGroups)
        {
            if (categoryId == MedicalInfoCategoryPrototype.Default)
                return;

            var category = _prototypeManager.Index<MedicalInfoCategoryPrototype>(categoryId);

            // need to fix this
            var dividerContainer = new PanelContainer
            {
                HorizontalExpand = true,
                Margin = new Thickness(5,10),
                SetSize = new Vector2(0, 2),
                PanelOverride = new StyleBoxFlat(Color.FromHex("#202028")),
            };

            var container = new BoxContainer
            {
                Margin = new Thickness(5),
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Name = category.Name,
            };

            container.AddChild(new Label
            {
                Text = Loc.GetString(category.Name),
                Margin = new Thickness(5),
            });

            MedicalInfoContainer.AddChild(container);
            MedicalInfoContainer.AddChild(dividerContainer);

            // tldr remove last child if its the divider
            // if MedicalInfoContainer.Children.LastItem == dividerContainer
            // MedicalInfoContainer.Remove( dividercontainer / lastItem )

            List<RecordChecklistEntry> selectors = new();

            foreach (var infoProto in categoryInfo)
            {
                var trait = _prototypeManager.Index<MedicalInfoPrototype>(infoProto);
                var selector = new RecordChecklistEntry(Loc.GetString(trait.Name));

                selector.Preference = _records.MedicalInfo.Contains(trait.ID) == true;

                selector.PreferenceChanged += preference =>
                {
                    if (preference)
                    {
                        UpdateRecords(_records.WithMedicalInfo(trait.ID, _prototypeManager));
                    }
                    else
                    {
                        UpdateRecords(_records.WithoutMedicalInfo(trait.ID, _prototypeManager));
                    }

                    // need something here to not force players to save if
                    // changes = default/prior profile
                    // ex. checking and unchecking the same box
                    UpdateRecords(_records);
                };
                selectors.Add(selector);
            }

            foreach (var selector in selectors) { container.AddChild(selector); }
        }
    }
}
