using Content.Shared.Preferences;
using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client._CD.Records.UI;

/// <summary>
/// The record editor tab that gets "injected" into the character editor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RecordEditorGui : Control
{
    /// <summary>
    /// Delegate that tells the editor to save records when the save button is pressed
    /// </summary>
    private readonly Action<PlayerProvidedCharacterRecords> _updateProfileRecords;

    private PlayerProvidedCharacterRecords _records = default!;

    public RecordEditorGui(Action<PlayerProvidedCharacterRecords> updateProfileRecords)
    {
        RobustXamlLoader.Load(this);
        _updateProfileRecords = updateProfileRecords;
    }
}
