// SPDX-FileCopyrightText: 2025 corresp0nd <46357632+corresp0nd@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using System.Linq;
using System.Numerics;
using Content.Shared.Preferences;
using Content.Shared._Funkystation.Records;
using Content.Client._CD.Records.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Medical.Records.UI;

/// <summary>
/// The record editor tab that gets "injected" into the character editor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RecordEditorGui : Control
{
    /// <summary>
    /// Delegate that tells the editor to save records when the save button is pressed
    /// </summary>
    private readonly Action<PlayerProvidedCharacterRecords> _updateProfileRecords;

    private readonly IPrototypeManager _prototypeManager;
    private PlayerProvidedCharacterRecords _records = default!;
    private readonly ISawmill _sawmill = default!;

    public RecordEditorGui(Action<PlayerProvidedCharacterRecords> updateProfileRecords, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _updateProfileRecords = updateProfileRecords;
        _prototypeManager = prototypeManager;

        #region Dropdowns

        // add options to each dropdown depending on the enums
        foreach (var insuranceProvider in Enum.GetValues<InsuranceProviders>())
        {
            AddInsuranceProvider(insuranceProvider);
        }

        foreach (var insurancetype in Enum.GetValues<InsuranceTypes>())
        {
            AddInsuranceType(insurancetype);
        }

        foreach (var bloodtype in Enum.GetValues<BloodTypes>())
        {
            AddBloodType(bloodtype);
        }

        #endregion

        #region General Information

        HeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newHeight))
                return;
            UpdateImperialHeight(newHeight);
            UpdateRecords(_records.WithHeight(newHeight));
        };

        WeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newWeight))
                return;
            UpdateImperialWeight(newWeight);
            UpdateRecords(_records.WithWeight(newWeight));
        };

        IdentifyingFeaturesEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithIdentifyingFeatures(args.Text));
        };

        WorkAuthCheckBox.OnToggled += args =>
        {
            UpdateRecords(_records.WithWorkAuth(args.Pressed));
        };

        InsuranceCheckBox.OnToggled += args =>
        {
            UpdateRecords(_records.WithInsurance(args.Pressed));
        };

        InsuranceCompanyDropdown.OnItemSelected += args =>
        {
            UpdateRecords(_records.WithInsuranceProvider(args.Id));
        };

        InsurancePlanDropdown.OnItemSelected += args =>
        {
            UpdateRecords(_records.WithInsuranceType(args.Id));
        };

        #endregion

        #region Medical Information

        BloodTypeDropdown.OnItemSelected += args =>
        {
            UpdateRecords(_records.WithBloodType(args.Id));
        };

        PostmortemEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithPostmortemInstructions(args.Text));
        };

        #endregion
    }

    public void Update(HumanoidCharacterProfile? profile)
    {
        _records = profile?.CDCharacterRecords ?? PlayerProvidedCharacterRecords.DefaultRecords();
        UpdateWidgets();
    }

    /// <param name="records"></param>
    /// <param name="updateWidgets">
    /// in some cases we don't want to update the widgets along with the records,
    /// because doing so will refresh any scrollboxes
    /// </param>
    private void UpdateRecords(PlayerProvidedCharacterRecords records, bool updateWidgets = true)
    {
        records.EnsureValid();
        _records = records;
        _updateProfileRecords(_records);

        if (updateWidgets)
            UpdateWidgets();
    }

    private void UpdateWidgets()
    {
        // general information
        HeightEdit.SetText(_records.Height.ToString());
        UpdateImperialHeight(_records.Height);
        WeightEdit.SetText(_records.Weight.ToString());
        UpdateImperialWeight(_records.Weight);

        IdentifyingFeaturesEdit.SetText(_records.IdentifyingFeatures);

        WorkAuthCheckBox.Pressed = _records.HasWorkAuthorization;

        InsuranceCheckBox.Pressed = _records.HasInsurance;

        // no insurance? then no insurance company or plan. sorry.
        // feels kinda nasty but whatever
        if (_records.HasInsurance == false)
        {
            InsuranceCompanyDropdown.SelectId(0);
            InsuranceCompanyDropdown.Disabled = true;

            InsurancePlanDropdown.SelectId(0);
            InsurancePlanDropdown.Disabled = true;
        }
        else
        {
            InsuranceCompanyDropdown.Disabled = false;
            InsuranceCompanyDropdown.SelectId(_records.InsuranceProvider);

            InsurancePlanDropdown.Disabled = false;
            InsurancePlanDropdown.SelectId(_records.InsuranceType);
        }

        // medical information
        BloodTypeDropdown.SelectId(_records.BloodType);
        PostmortemEdit.SetText(_records.PostmortemInstructions);

        RefreshMedicalInformation();
    }

    /* height/weight updating and conversion */
    private void UpdateImperialHeight(int newHeight)
    {
        HeightImperialLabel.Text = UnitConversion.GetImperialDisplayLength(newHeight);
    }

    private void UpdateImperialWeight(int newWeight)
    {
        WeightImperialLabel.Text = UnitConversion.GetImperialDisplayMass(newWeight);
    }

    /* insurance dropdowns */
    private void AddInsuranceProvider(InsuranceProviders provider)
    {
        var name = Loc.GetString($"character-records-insurance-provider-{provider.ToString().ToLower()}");
        InsuranceCompanyDropdown.AddItem(name, (int)provider);
    }

    private void AddInsuranceType(InsuranceTypes type)
    {
        var name = Loc.GetString($"character-records-insurance-type-{type.ToString().ToLower()}");
        InsurancePlanDropdown.AddItem(name, (int)type);
    }

    /* blood type dropdown */
    private void AddBloodType(BloodTypes type)
    {
        var name = Loc.GetString($"character-records-blood-{type.ToString().ToLower()}");
        BloodTypeDropdown.AddItem(name, (int)type);
    }

    private void RefreshMedicalInformation()
    {
        MedicalInfoContainer.DisposeAllChildren();

        var info = _prototypeManager.EnumeratePrototypes<MedicalInfoPrototype>()
            .OrderBy(t => Loc.GetString(t.Name))
            .ToList();

        // if there's no prototypes, generate a default label
        if (info.Count < 1)
        {
            MedicalInfoContainer.AddChild(new Label
            {
                Text = Loc.GetString("medical-info-no-info"),
                FontColorOverride = Color.Gray,
            });
            return;
        }

        Dictionary<string, List<string>> infoGroups = new();

        foreach (var entry in info)
        {
            if (entry.Category == null || entry.Category == MedicalInfoCategoryPrototype.Default)
            {
                _sawmill.Warning($"Medical Info prototype {entry.ID} is missing a category (current category: {entry.Category}) and will be skipped.");
                continue;
            }

            var group = infoGroups.GetOrNew(entry.Category);
            group.Add(entry.ID);
        }

        // organize the dictionary after it gens so it stops randomizing the order of the columns
        infoGroups.OrderBy(t => t);

        // setup ui
        foreach (var (categoryId, categoryInfo) in infoGroups)
        {
            if (categoryId == MedicalInfoCategoryPrototype.Default)
                return;

            var category = _prototypeManager.Index<MedicalInfoCategoryPrototype>(categoryId);

            // having to define all of these different containers
            // to get the layout feels wrong but whatever
            var dividerContainer = new PanelContainer
            {
                VerticalExpand = true,
                Margin = new Thickness(5,10),
                SetWidth = 2,
                PanelOverride = new StyleBoxFlat(Color.FromHex("#202028")),
            };

            var container = new ScrollContainer
            {
                HorizontalExpand = true,
                HScrollEnabled = false,
                Margin = new Thickness(10,5),
                SetHeight = 300f,
            };

            var layout = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

            layout.AddChild(new Label
            {
                Text = Loc.GetString(category.Name),
                Margin = new Thickness(5),
                Align = Label.AlignMode.Center,
            });

            container.AddChild(layout);
            MedicalInfoContainer.AddChild(container);

            // don't add the divider if its the last entry
            if (categoryId != infoGroups.Keys.Last())
                MedicalInfoContainer.AddChild(dividerContainer);

            List<RecordChecklistEntry> selectors = new();

            foreach (var infoProto in categoryInfo)
            {
                var trait = _prototypeManager.Index<MedicalInfoPrototype>(infoProto);
                var selector = new RecordChecklistEntry(Loc.GetString(trait.Name));

                selector.Preference = _records.MedicalInfo.Contains(trait.ID) == true;

                selector.PreferenceChanged += preference =>
                {
                    UpdateRecords(preference
                        ? _records.WithMedicalInfo(trait.ID, _prototypeManager)
                        : _records.WithoutMedicalInfo(trait.ID, _prototypeManager),
                        false);
                    UpdateRecords(_records, false);
                };

                selectors.Add(selector);
            }
            foreach (var selector in selectors) { layout.AddChild(selector); }
        }
    }
}
