using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Funkystation.Medical.Records.UI;

/// <summary>
/// For generating a new checklist entry for allergies, prescriptions, family history
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RecordChecklistEntry : BoxContainer
{
    public event Action<bool>? PreferenceChanged;

    private readonly CheckBox _checkbox;
    private readonly Label _label;

    public bool Preference
    {
        get => ItemCheckBox.Pressed;
        set => ItemCheckBox.Pressed = value;
    }
    public RecordChecklistEntry(string name)
    {
        _checkbox = ItemCheckBox;
        _label = ItemLabel;

        _label.Text = name;

        _checkbox.OnToggled += OnCheckBoxToggled;
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        PreferenceChanged?.Invoke(args.Pressed);
    }
}
