using System;
using System.Numerics;
using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.Prototypes;
using Robust.Shared.Input;
using Range = Robust.Client.UserInterface.Controls.Range;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Content.Shared.Atmos;
using static Content.Shared.Atmos.Components.GasAnalyzerComponent;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client._Funkystation.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a <see cref="SharedBluespaceSenderComponent"/>
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class BluespaceSenderWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        public event Action<int>? RetrieveButtonPressed;
        public event Action<int>? EnableGasForSell;

        [DataField("gasList")]
        public List<Gas> GasList = new()
        {
            Gas.Oxygen,
            Gas.Nitrogen,
            Gas.CarbonDioxide,
            Gas.Plasma,
            Gas.Tritium,
            Gas.WaterVapor,
            Gas.Ammonia,
            Gas.NitrousOxide,
            Gas.Frezon,
            Gas.BZ, // Assmos - /tg/ gases
            Gas.Healium, // Assmos - /tg/ gases
            Gas.Nitrium, // Assmos - /tg/ gases
            Gas.Pluoxium, // Assmos - /tg/ gases
            Gas.Hydrogen, // Assmos - /tg/ gases
        };
        
        public BluespaceSenderWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        public void BuildGasList(List<bool>? enabledGases, List<bool>? retrievingGases)
        {
            GasListBox.Children.Clear();

            foreach (var gas in GasList.Select((name, i) => new { i, name }))
            {
                var gasName = gas.name;
                var index = gas.i;

                var GasBox = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true
                };

                var TopRow = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true
                };

                var GasName = new Label
                {
                    Text = $"{gasName}"
                };

                var GasAmount = new Label
                {
                    Name = "GasAmount",
                    Text = "0.00"
                };

                var LeftSide = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    VerticalAlignment = VAlignment.Top
                };

                var EnableGasForSellCheckBox = new CheckBox
                {
                    Name = $"{gasName}Enable",
                    Pressed = enabledGases != null && enabledGases[index]
                };

                var CheckBoxLabel = new Label
                {
                    Text = "Enable "
                };

                var CheckBoxBox = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalAlignment = HAlignment.Right
                };
                
                var RetrieveButton = new Button
                {
                    Name = "RetrieveButton",
                    Text = retrievingGases != null && retrievingGases[index] ? "Retrieving" : "Retrieve"
                };

                RetrieveButton.OnPressed += _ => RetrieveButtonPressed?.Invoke(index);
                EnableGasForSellCheckBox.OnToggled += _ => EnableGasForSell?.Invoke(index);

                LeftSide.Children.Add(GasName);
                LeftSide.Children.Add(GasAmount);
                CheckBoxBox.Children.Add(CheckBoxLabel);
                CheckBoxBox.Children.Add(EnableGasForSellCheckBox);
                TopRow.Children.Add(LeftSide);
                TopRow.Children.Add(new Control { HorizontalExpand = true });
                TopRow.Children.Add(CheckBoxBox);

                GasBox.Children.Add(TopRow);
                GasBox.Children.Add(RetrieveButton);

                GasListBox.Children.Add(GasBox);
            }
        }

        public void SetBluespaceGasMixture(GasMixture? bluespaceGasMixture)
        {
            if (bluespaceGasMixture == null)
            {
                return;
            }

            for (int i = 0; i < GasListBox.Children.Count(); i++)
            {
                var gasBox = GasListBox.Children.ElementAt(i) as BoxContainer;
                if (gasBox == null) continue;
                // Find the GasAmount label within this GasBox
                var gasAmountLabel = gasBox.Children.First().Children.First().Children.ElementAt(1) as Label;
                if (gasAmountLabel != null)
                {
                    // Update the label with the moles (or pressure) of this gas
                    float moles = bluespaceGasMixture.GetMoles(i); // Assuming GasMixture has GetMoles
                    gasAmountLabel.Text = moles.ToString("F2"); // Format to 2 decimal places
                }
            }
        }
    }
}
