using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Content.Shared.Temperature;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using static Content.Shared.Atmos.Components.GasAnalyzerComponent;
using Content.Shared.Atmos.Components;

namespace Content.Client._Funkystation.Atmos.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GasPipeSensorWindow : DefaultWindow
    {
        public GasPipeSensorWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void Populate(GasPipeSensorUserMessage msg)
        {
            CTopBox.RemoveAllChildren();
            CPipeContent.RemoveAllChildren();

            if (msg.PipeMix is null)
            {
                CTopBox.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-no-data")
                });
                return;
            }

            var mix = msg.PipeMix.Value;

            // Generate the exact same gas display style as gas analyzer
            GenerateGasDisplay(mix, CPipeContent);

            // Adjust window size to content
            MinSize = new Vector2(CPipeContent.DesiredSize.X + 40, MinSize.Y);
        }

        private void GenerateGasDisplay(GasMixEntry gasMix, Control parent)
        {
            var panel = new PanelContainer
            {
                VerticalExpand = true,
                HorizontalExpand = true,
                Margin = new Thickness(4),
                PanelOverride = new StyleBoxFlat { BorderColor = Color.FromHex("#4f4f4f"), BorderThickness = new Thickness(1) }
            };

            var dataContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                VerticalExpand = true,
                Margin = new Thickness(4)
            };

            parent.AddChild(panel);
            panel.AddChild(dataContainer);

            // Volume
            var volBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            volBox.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-volume-text") });
            volBox.AddChild(new Control { MinSize = new Vector2(10, 0), HorizontalExpand = true });
            volBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-volume-val-text", ("volume", $"{gasMix.Volume:0.##}")),
                Align = Label.AlignMode.Right,
                HorizontalExpand = true
            });
            dataContainer.AddChild(volBox);

            // Pressure
            var presBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            presBox.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-pressure-text") });
            presBox.AddChild(new Control { MinSize = new Vector2(10, 0), HorizontalExpand = true });
            presBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-pressure-val-text", ("pressure", $"{gasMix.Pressure:0.##}")),
                Align = Label.AlignMode.Right,
                HorizontalExpand = true
            });
            dataContainer.AddChild(presBox);

            // Temperature (skip if no meaningful pressure)
            if (gasMix.Pressure > Atmospherics.GasMinMoles)
            {
                var tempBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
                tempBox.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-temperature-text") });
                tempBox.AddChild(new Control { MinSize = new Vector2(10, 0), HorizontalExpand = true });
                tempBox.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-temperature-val-text",
                        ("tempK", $"{gasMix.Temperature:0.#}"),
                        ("tempC", $"{TemperatureHelpers.KelvinToCelsius(gasMix.Temperature):0.#}")),
                    Align = Label.AlignMode.Right,
                    HorizontalExpand = true
                });
                dataContainer.AddChild(tempBox);
            }

            if (gasMix.Gases == null || gasMix.Gases.Length == 0)
            {
                dataContainer.AddChild(new Control { MinSize = new Vector2(0, 10) });
                dataContainer.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-no-gas-text"),
                    FontColorOverride = Color.Gray
                });
                return;
            }

            dataContainer.AddChild(new Control { MinSize = new Vector2(0, 10) });

            // Gas table
            var tableKey = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            var tableVal = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            var tablePercent = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

            dataContainer.AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
                {
                    tableKey,
                    new Control { MinSize = new Vector2(10, 0), HorizontalExpand = true },
                    tableVal,
                    new Control { MinSize = new Vector2(10, 0), HorizontalExpand = true },
                    tablePercent
                }
            });

            var gasBar = new SplitBar
            {
                MinHeight = 30,
                MinBarSize = new Vector2(12, 0)
            };

            dataContainer.AddChild(new Control { MinSize = new Vector2(0, 10), VerticalExpand = true });

            float totalGasAmount = 0f;
            foreach (var gas in gasMix.Gases)
                totalGasAmount += gas.Amount;

            tableKey.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-gas-column-name"), Align = Label.AlignMode.Center });
            tableVal.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-molarity-column-name"), Align = Label.AlignMode.Center });
            tablePercent.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-percentage-column-name"), Align = Label.AlignMode.Center });

            tableKey.AddChild(new StripeBack());
            tableVal.AddChild(new StripeBack());
            tablePercent.AddChild(new StripeBack());

            for (var j = 0; j < gasMix.Gases.Length; j++)
            {
                var gas = gasMix.Gases[j];
                var color = Color.FromHex($"#{gas.Color}", Color.White);

                tableKey.AddChild(new Label { Text = Loc.GetString(gas.Name) });
                tableVal.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-molarity-text", ("mol", $"{gas.Amount:0.00}")),
                    Align = Label.AlignMode.Right
                });
                tablePercent.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-percentage-text",
                        ("percentage", $"{(gas.Amount / totalGasAmount * 100):0.0}")),
                    Align = Label.AlignMode.Right
                });

                gasBar.AddEntry(gas.Amount, color, tooltip: Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                    ("gasName", gas.Name),
                    ("amount", $"{gas.Amount:0.##}"),
                    ("percentage", $"{(gas.Amount / totalGasAmount * 100):0.#}")));
            }

            dataContainer.AddChild(gasBar);
        }
    }
}
