using System;
using System.Globalization;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Funkystation.Atmos.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class TemperatureGateWindow : DefaultWindow
    {
        public bool Enabled { get; private set; } = false;
        public float Threshold { get; private set; } = 273.15f;
        public bool IsMinMode { get; private set; } = false; // false = Max mode

        public event Action? OnStatusToggled;
        public event Action<float, bool>? OnThresholdAndModeSet;

        private float _lastSentThreshold = 273.15f;
        private bool _lastSentIsMinMode = false;

        public TemperatureGateWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // Status toggle
            ToggleStatusButton.OnPressed += _ =>
            {
                Enabled = !Enabled;
                UpdateStatusButton();
                OnStatusToggled?.Invoke();
            };

            // Enable Set if valid & changed
            ThresholdInput.OnTextChanged += _ => UpdateSetButtonState();

            // Mode toggle
            ToggleModeButton.OnPressed += _ =>
            {
                IsMinMode = !IsMinMode;
                UpdateModeButton();
                UpdateSetButtonState();
            };

            // Set button
            SetButton.OnPressed += _ =>
            {
                if (TryParseThreshold(out var newThreshold))
                {
                    Threshold = newThreshold;
                    _lastSentThreshold = newThreshold;
                    _lastSentIsMinMode = IsMinMode;

                    OnThresholdAndModeSet?.Invoke(newThreshold, IsMinMode);
                    UpdateSetButtonState(); // will disable it
                }
            };

            // Initial visual state
            UpdateStatusButton();
            UpdateModeButton();
            SetThreshold(273.15f); // initial display
        }

        public void SetStatus(bool enabled)
        {
            Enabled = enabled;
            UpdateStatusButton();
        }

        public void SetThreshold(float kelvin)
        {
            Threshold = kelvin;
            ThresholdInput.Text = kelvin.ToString("F2", CultureInfo.CurrentCulture);
            _lastSentThreshold = kelvin;
            UpdateSetButtonState();
        }

        public void SetMode(bool isMinMode)
        {
            IsMinMode = isMinMode;
            _lastSentIsMinMode = isMinMode;
            UpdateModeButton();
            UpdateSetButtonState();
        }

        private void UpdateStatusButton()
        {
            ToggleStatusButton.Text = Enabled
                ? Loc.GetString("temperature-gate-ui-status-enabled")
                : Loc.GetString("temperature-gate-ui-status-disabled");
        }

        private void UpdateModeButton()
        {
            ToggleModeButton.Text = IsMinMode
                ? Loc.GetString("temperature-gate-ui-mode-min")
                : Loc.GetString("temperature-gate-ui-mode-max");
        }

        private void UpdateSetButtonState()
        {
            bool isValid = TryParseThreshold(out _);
            bool changed = isValid &&
                 (Math.Abs(float.Parse(ThresholdInput.Text!, CultureInfo.InvariantCulture) - _lastSentThreshold) > 0.001f ||
                 IsMinMode != _lastSentIsMinMode);

            SetButton.Disabled = !isValid || !changed;
        }

        private bool TryParseThreshold(out float value)
        {
            value = 0f;
            var text = ThresholdInput.Text?.Trim() ?? "";

            if (string.IsNullOrEmpty(text))
                return false;

            return float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out value);
        }
    }
}
