# SPDX-FileCopyrightText: 2024 Fenn <162015305+TooSillyFennec@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 John Space <bigdumb421@gmail.com>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 fishbait <gnesse@gmail.com>
# SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 username <113782077+whateverusername0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 pa.pecherskij <pa.pecherskij@interfax.ru>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  id: BaseGameRuleDynamic
  abstract: true
  components:
  - type: GameRule
  - type: DynamicRuleset
    nameLoc: dynamic-gamerule-unknown-title

- type: entity
  abstract: true
  parent: BaseGameRuleDynamic
  id: BaseTraitorRuleDynamic
  components:
  - type: TraitorRule
  - type: AntagRandomObjectives
    sets:
    - groups: TraitorObjectiveGroups
    maxDifficulty: 6 # Funky Station - Fixes upstream objective hell
  - type: AntagSelection
    agentName: traitor-round-end-agent-name

- type: entity
  abstract: true
  parent: BaseGameRuleDynamic
  id: BaseNukeopsRuleDynamic
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesOperationPrefix
    - NamesOperationSuffix
  - type: NukeopsRule
  - type: RuleGrids
  - type: AntagSelection
  - type: AntagLoadProfileRule
    speciesOverride: Human
    speciesOverrideBlacklist:
    - Vox # lol loser

- type: entity
  abstract: true
  parent: BaseGameRuleDynamic
  id: BaseBlobRuleDynamic
  components:
  - type: BlobRule
