using System.Diagnostics.CodeAnalysis;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Power.Generation.FissionGenerator;
using Content.Shared.Atmos;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Power.UI;

/// <summary>
/// Client-side UI used to view a nuclear reactor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NuclearReactorWindow : FancyWindow
{

    private StyleBoxFlat[,] _reactorGrid;
    private TextureRect[,] _reactorRect = new TextureRect[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];

    private double[,] _temperatureGrid = new double[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];
    private int[,] _neutronGrid = new int[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];
    private string[,] _iconGrid = new string[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];
    private string[,] _partName = new string[NuclearReactorComponent.ReactorGridWidth , NuclearReactorComponent.ReactorGridHeight];

    // You thought 2 dimensions was bad
    private double[,,] _partInfo = new double[NuclearReactorComponent.ReactorGridWidth , NuclearReactorComponent.ReactorGridHeight , 3];

    private byte _displayMode = 1<<0;

    private int _targetX = 0;
    private int _targetY = 0;

    public event Action? ChangeViewButtonPressed;
    public event Action? XIncrementButtonPressed;
    public event Action? XDecrementButtonPressed;
    public event Action? YIncrementButtonPressed;
    public event Action? YDecrementButtonPressed;

    public event Action<Vector2d>? ItemActionButtonPressed;
    public event Action? EjectButtonPressed;

    public NuclearReactorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ChangeViewButton.OnPressed += _ => ChangeViewButtonPressed?.Invoke();
        XIncrement.OnPressed += _ => XIncrementButtonPressed?.Invoke();
        XDecrement.OnPressed += _ => XDecrementButtonPressed?.Invoke();
        YIncrement.OnPressed += _ => YIncrementButtonPressed?.Invoke();
        YDecrement.OnPressed += _ => YDecrementButtonPressed?.Invoke();
        ItemAction.OnPressed += _ => ItemActionButtonPressed?.Invoke(new(_targetY, _targetX));
        EjectItem.OnPressed += _ => EjectButtonPressed?.Invoke();

        ChangeViewButtonPressed += OnChangeViewButtonPressed;
        XIncrementButtonPressed += OnXIncrement;
        XDecrementButtonPressed += OnXDecrement;
        YIncrementButtonPressed += OnYIncrement;
        YDecrementButtonPressed += OnYDecrement;

        InitReactorGrid();
    }

    [MemberNotNull(nameof(_reactorGrid))]
    public void InitReactorGrid()
    {
        _reactorGrid = new StyleBoxFlat[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];
        _reactorRect = new TextureRect[NuclearReactorComponent.ReactorGridWidth, NuclearReactorComponent.ReactorGridHeight];

        for (var x = 0; x < NuclearReactorComponent.ReactorGridWidth; x++)
        {
            for (var y = 0; y < NuclearReactorComponent.ReactorGridHeight; y++)
            {
                var styleBox = new StyleBoxFlat();
                var icon = new TextureRect() { 
                    SetSize = new(32, 32), 
                    TexturePath = "/Textures/_FarHorizons/Structures/Power/Generation/FissionGenerator/reactor_part_inserted/base.png"
                };

                _reactorGrid[x,y] = styleBox;
                _reactorRect[x,y] = icon;

                var control = new PanelContainer
                {
                    Margin = new Thickness(2),
                    PanelOverride = styleBox,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                };
                control.AddChild(icon);
                ReactorGrid.AddChild(control);
            }
        }
    }

    public void Update(NuclearReactorBuiState msg)
    {
        Array.Clear(_temperatureGrid);
        Array.Clear(_neutronGrid);
        Array.Clear(_iconGrid);
        Array.Clear(_partName);
        Array.Clear(_partInfo);

        var zoff = NuclearReactorComponent.ReactorGridWidth * NuclearReactorComponent.ReactorGridHeight;

        for (var x = 0; x < NuclearReactorComponent.ReactorGridWidth; x++)
        {
            for (var y = 0; y < NuclearReactorComponent.ReactorGridHeight; y++)
            {
                var loc = (x * NuclearReactorComponent.ReactorGridWidth) + y;
                _temperatureGrid[x,y] = msg.TemperatureGrid[loc];
                _neutronGrid[x,y] = msg.NeutronGrid[loc];
                _iconGrid[x,y] = msg.IconGrid[loc];
                _partName[x,y] = msg.PartName[loc];
                _partInfo[x, y, 0] = msg.PartInfo[loc];
                _partInfo[x, y, 1] = msg.PartInfo[loc + zoff];
                _partInfo[x, y, 2] = msg.PartInfo[loc + (zoff * 2)];
            }
        }

        ItemName.Text = msg.ItemName ?? "empty";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        //Update the grid
        for (var x = 0; x < NuclearReactorComponent.ReactorGridWidth; x++)
        {
            for (var y = 0; y < NuclearReactorComponent.ReactorGridHeight; y++)
            {
                var box = _reactorGrid[x,y];
                if (_displayMode % 2 == 1)
                {
                    box.BackgroundColor = GetColor(293.15, 1200, _temperatureGrid[x, y]);
                    ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-temp");
                }
                else if ((_displayMode >> 1) % 2 == 1)
                {
                    box.BackgroundColor = GetColor(0, 5, _neutronGrid[x, y]);
                    ViewLabel.Text = Loc.GetString("comp-nuclear-reactor-ui-view-neutron");
                }

                if(_iconGrid[x, y] != null)
                    _reactorRect[x, y].TexturePath = "/Textures/_FarHorizons/Structures/Power/Generation/FissionGenerator/reactor_part_inserted/" + _iconGrid[x, y] + ".png";
            }
        }

        UpdateTargetInfo();
    }

    private static Color GetColor(double pointA, double pointB, double value)
    {
        var mid = pointA+((pointB-pointA) / 2);
        Color result;

        if (value < pointA && pointA > 0)
            result = Color.InterpolateBetween(Color.DarkBlue, Color.FromHex("#31843E"), (float)(value / pointA));
        else if (value >= pointA && value < mid)
            result = Color.InterpolateBetween(Color.FromHex("#31843E"), Color.FromHex("#BBBB00"), (float)((value - pointA) / (mid - pointA)));
        else if (value >= mid && value < pointB)
            result = Color.InterpolateBetween(Color.FromHex("#BBBB00"), Color.FromHex("#BB3232"), (float)((value - mid) / (pointB - mid)));
        else if (value >= pointB && value < pointB * 1.25)
            result = Color.FromHex("#BB3232");
        else if (value >= pointB * 1.25)
            result = Color.FromHex("#550000"); // Death.
        else
            result = Color.Black;

        return result;
    }

    private void OnChangeViewButtonPressed()
    {
        // The bits go marching one by one...
        _displayMode <<= 1;
        if (_displayMode >= 1 << 2)
            _displayMode = 1 << 0;
    }

    private void UpdateTargetInfo()
    {
        if (_partName[_targetY, _targetX] != null)
        {
            TargetName.Visible = true;
            TargetName.Text = _partName[_targetY, _targetX];
        }
        else
            TargetName.Visible = false;

        if (_temperatureGrid[_targetY, _targetX] != 0)
        {
            TargetTemperatureGrid.Visible = true;
            TargetTemperature.Text = Math.Round(_temperatureGrid[_targetY, _targetX]-Atmospherics.T0C, 2).ToString()+"C";
        }
        else
            TargetTemperatureGrid.Visible = false;

        if (_partInfo[_targetY, _targetX, 0] != 0)
        {
            TargetNRadiationGrid.Visible = true;
            TargetNRadiation.Text = Math.Round(_partInfo[_targetY, _targetX, 0], 2).ToString();
        }
        else
            TargetNRadiationGrid.Visible = false;

        if (_partInfo[_targetY, _targetX, 1] != 0)
        {
            TargetRadiationGrid.Visible = true;
            TargetRadiation.Text = Math.Round(_partInfo[_targetY, _targetX, 1], 2).ToString();
        }
        else
            TargetRadiationGrid.Visible = false;

        if (_partInfo[_targetY, _targetX, 2] != 0)
        {
            TargetSpentGrid.Visible = true;
            TargetSpent.Text = Math.Round(_partInfo[_targetY, _targetX, 2], 2).ToString();
        }
        else
            TargetSpentGrid.Visible = false;
    }

    #region Move Target
    private void OnXIncrement()
    {
        if (_targetX >= NuclearReactorComponent.ReactorGridWidth - 1)
        {
            XIncrement.Disabled = true;
            return;
        }

        _targetX++;
        XPos.Text = _targetX.ToString();

        XIncrement.Disabled = _targetX >= NuclearReactorComponent.ReactorGridWidth - 1;
        XDecrement.Disabled = _targetX <= 0;
    }

    private void OnXDecrement()
    {
        if (_targetX <= 0)
        {
            XDecrement.Disabled = true;
            return;
        }

        _targetX--;
        XPos.Text = _targetX.ToString();

        XIncrement.Disabled = _targetX >= NuclearReactorComponent.ReactorGridWidth - 1;
        XDecrement.Disabled = _targetX <= 0;
    }

    private void OnYIncrement()
    {
        if (_targetY >= NuclearReactorComponent.ReactorGridWidth - 1)
        {
            YIncrement.Disabled = true;
            return;
        }

        _targetY++;
        YPos.Text = _targetY.ToString();

        YIncrement.Disabled = _targetY >= NuclearReactorComponent.ReactorGridHeight - 1;
        YDecrement.Disabled = _targetY <= 0;
    }

    private void OnYDecrement()
    {
        if (_targetY <= 0)
        {
            YDecrement.Disabled = true;
            return;
        }

        _targetY--;
        YPos.Text = _targetY.ToString();

        YIncrement.Disabled = _targetY >= NuclearReactorComponent.ReactorGridHeight - 1;
        YDecrement.Disabled = _targetY <= 0;
    }
    #endregion

    public void SetItemName(string? itemName) => ItemName.Text = itemName ?? "empty";
}