# SPDX-FileCopyrightText: 2025 IronDragoon <8961391+IronDragoon@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  parent: BoxCardboard
  id: BoxTapeRecorder
  name: tape recorder box
  description: A box with colorful cassette tapes and a tape recorder.
  components:
  - type: Sprite
    layers:
    - state: box_security
    - sprite: _DV/Objects/Storage/boxes.rsi
      state: recorder
  - type: StorageFill
    contents:
    - id: CassetteTape
      amount: 4
    - id: TapeRecorder
