# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 HS <81934438+HolySSSS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 no <165581243+pissdemon@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

# for important antag roles (nukie reinforcements, ninja, etc.)
- type: ghostRoleRaffleSettings
  id: default
  settings:
    initialDuration: 30
    joinExtendsDurationBy: 10
    maxDuration: 90

# for roles that don't matter too much or are available plentifully (e.g. space carp)
- type: ghostRoleRaffleSettings
  id: short
  settings:
    initialDuration: 10
    joinExtendsDurationBy: 2
    maxDuration: 15
