# SPDX-FileCopyrightText: 2023 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 2023 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Carolyn3114 <136143032+Carolyn3114@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Flareguy <78941145+Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Julian Giebel <juliangiebel@live.de>
# SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2024 PoTeletubby <ajcraigaz@gmail.com>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 Ubaser <134914314+UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Vasilis <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Mish <bluscout78@yahoo.com>
# SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 heree <79546981+hereelabs@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 hereelabs <hahmorm@gmail.com>
# SPDX-FileCopyrightText: 2025 pa.pecherskij <pa.pecherskij@interfax.ru>
# SPDX-FileCopyrightText: 2025 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
      orders:
        Cargo: [ ]
        Engineering: [ ]
        Medical: [ ]
        Science: [ ]
        Security: [ ]
        Service: [ ]
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        trade: !type:GridSpawnGroup
          addComponents:
            - type: ProtectedGrid
            - type: TradeStation
          paths:
            - /Maps/Shuttles/trading_outpost.yml
        mining: !type:GridSpawnGroup
          paths:
          - /Maps/_Funkystation/Shuttles/mining.yml #funky
        oldstation: !type:GridSpawnGroup #force this to always spawn so ghost roles are always accessible
          minimumDistance: 950 #unlikely to work
          maximumDistance: 1200
          stationGrid: false
          paths:
          - /Maps/_Funkystation/Ruins/oldstation.yml
        # Spawn last
        ruins: !type:GridSpawnGroup
          hide: true
          nameGrid: true
          minCount: 2
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/abandoned_outpost.yml
          - /Maps/Ruins/chunked_tcomms.yml
          - /Maps/Ruins/biodome_satellite.yml
          - /Maps/Ruins/derelict.yml
          - /Maps/Ruins/djstation.yml
          - /Maps/Ruins/empty_flagship.yml
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/ruined_prison_ship.yml
          - /Maps/Ruins/syndicate_dropship.yml
          - /Maps/Ruins/whiteship_ancient.yml
          - /Maps/Ruins/whiteship_bluespacejumper.yml
          - /Maps/Ruins/wrecklaimer.yml
        vgroid: !type:DungeonSpawnGroup
          minimumDistance: 300
          maximumDistance: 350
          nameDataset: NamesBorer
          stationGrid: false
          addComponents:
          - type: Gravity
            enabled: true
            inherent: true
          protos:
          - VGRoid

- type: entity
  id: BaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.
