- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolPlasma
  name: P-25 phoron pistol safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPlasmaAdder
      amount: 4
    - id: EchionCanister
      amount: 8

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRiflePlasma
  name: P-106 phoron rifle safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPlasmaAkurra
      amount: 4
    - id: EchionCanister
      amount: 12

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolRg2
  name: RG-2 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGunEnergyPistol
      amount: 4