// SPDX-FileCopyrightText: 2025 Gansu <68031780+GansuLalan@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
// SPDX-FileCopyrightText: 2025 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.Message;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyHistoryEntry : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public BountyHistoryEntry(CargoBountyHistoryData bounty)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var items = new List<string>();
        foreach (var entry in bounty.Bounty.Entries) // Funky Station
        {
            items.Add(Loc.GetString("bounty-console-manifest-entry",
                ("amount", entry.Amount),
                ("item", Loc.GetString(entry.Name))));
        }

        ManifestLabel.SetMarkup(Loc.GetString("bounty-console-manifest-label", ("item", string.Join(", ", items))));
        RewardLabel.SetMarkup(Loc.GetString("bounty-console-reward-label", ("reward", bounty.Bounty.Reward))); // Funky Station
        IdLabel.SetMarkup(Loc.GetString("bounty-console-id-label", ("id", bounty.Id)));

        TimestampLabel.SetMarkup(bounty.Timestamp.ToString(@"hh\:mm\:ss"));

        if (bounty.Result == CargoBountyHistoryData.BountyResult.Completed)
        {
            NoticeLabel.SetMarkup(Loc.GetString("bounty-console-history-notice-completed-label"));
        }
        else
        {
            NoticeLabel.SetMarkup(Loc.GetString("bounty-console-history-notice-skipped-label",
                ("id", bounty.ActorName ?? "")));
        }
    }
}
