# SPDX-FileCopyrightText: 2026 TrixxedHeart <46364955+TrixxedBit@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: antagCategory
  id: Solo
  name: antag-category-solo

- type: antagCategory
  id: Team
  name: antag-category-team

- type: antagCategory
  id: Other
  name: antag-category-other

