using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;

namespace Content.Client._Funkystation.Medical.MedicalRecords.UI;


[GenerateTypedNameReferences]
public sealed partial class MedicalRecordsEntry : FancyWindow
{
}
