- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:RoleTimeRequirement
      role: JobRoboticist
      time: 18000 #5 hrs
    - !type:RoleTimeRequirement
      role: JobScientist
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Science
      time: 72000 #20 hrs
    - !type:OverallPlaytimeRequirement
      time: 90000 #25 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Robotics # funkystation
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  - External # goobstation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
  storage:
    back:
    - Flash
