# SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 pa.pecherskij <pa.pecherskij@interfax.ru>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: antag
  id: GenericAntagonist
  name: roles-antag-generic-solo-antagonist-name
  antagonist: true
  objective: never-shown

- type: antag
  id: GenericTeamAntagonist
  name: roles-antag-generic-team-antagonist-name
  antagonist: true
  objective: never-shown

- type: antag
  id: GenericFreeAgent
  name: roles-antag-generic-free-agent-name
  antagonist: true
  objective: never-shown

- type: antag
  id: GenericSiliconAntagonist
  name: roles-antag-generic-silicon-antagonist-name
  antagonist: true
  objective: never-shown
