# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Kira Bridgeton <161087999+Verbalase@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 PoTeletubby <108604614+PoTeletubby@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 PoTeletubby <ajcraigaz@gmail.com>
# SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: antag
  id: Survivor
  name: roles-antag-survivor-name
  antagonist: true
  objective: roles-antag-survivor-objective
  # guides: [  ]

- type: antag
  id: Wizard
  name: roles-antag-wizard-name
  antagonist: true
  setPreference: true
  objective: roles-antag-wizard-objective # TODO: maybe give random objs and stationary ones from AntagObjectives and AntagRandomObjectives
  requirements: # I hate time locked roles but this should be enough time for someone to be acclimated
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ Wizard ]

# See wizard_startinggear for wiz start gear options
