using Content.Client.Message;
using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class AntagSelector : PanelContainer
{
    public event Action? OnGuidebookClicked;

    [Dependency] private readonly IResourceCache _resCache = default!;

    private readonly TextureRect _icon;
    private readonly Label _antagName;
    private readonly RichTextLabel _antagDescription;
    private readonly Button _guidebookButton;
    private readonly Control _preferenceSelector;
    private readonly Control _iconWrapper;
    private readonly PanelContainer _iconPanel;
    private readonly BoxContainer _buttonsContainer;

    public AntagSelector()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _icon = FindControl<TextureRect>("Icon")!;
        _antagName = FindControl<Label>("AntagName")!;
        _antagDescription = FindControl<RichTextLabel>("AntagDescription")!;
        _guidebookButton = FindControl<Button>("GuidebookButton")!;
        _preferenceSelector = FindControl<Control>("PreferenceSelector")!;
        _iconWrapper = FindControl<Control>("IconWrapper")!;
        _iconPanel = FindControl<PanelContainer>("IconPanel")!;
        _buttonsContainer = FindControl<BoxContainer>("ButtonsContainer")!;

        _guidebookButton.OnPressed += _ => OnGuidebookClicked?.Invoke();

        // this is probably not necessary but idgaf, makes sure icon stays square
        _buttonsContainer.OnResized += () =>
        {
            var height = _buttonsContainer.Height;
            _iconWrapper.SetWidth = height;
            _iconWrapper.SetHeight = height;
            _iconPanel.SetWidth = height;
            _iconPanel.SetHeight = height;
        };
    }

    public void SetIcon(Texture? icon)
    {
        _icon.Texture = icon;
    }

    public void SetName(string name)
    {
        _antagName.Text = name;

        // Scale font size based on name length to fit available space
        var baseSize = 20;
        var maxLength = 18;

        if (name.Length > maxLength)
        {
            // Scale down the font size based on how much longer the name is
            var scaleFactor = (float)maxLength / name.Length;
            var newSize = (int)(baseSize * scaleFactor);
            // Don't go smaller than 12
            newSize = Math.Max(newSize, 12);

            _antagName.FontOverride = _resCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", newSize);
        }
        else
        {
            _antagName.FontOverride = null;
        }
    }


    public void SetDescription(string description)
    {
        _antagDescription.SetMarkupPermissive(description);
    }

    public void SetPreferenceSelector(Control selector)
    {
        _preferenceSelector.AddChild(selector);
    }
}
