// SPDX-FileCopyrightText: 2024 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Janet Blackquill <uhhadd@gmail.com>
// SPDX-FileCopyrightText: 2025 YaraaraY <158123176+YaraaraY@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 corresp0nd <46357632+corresp0nd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Shared.Roles;
using System.Linq;

namespace Content.Client.Lobby.UI.Roles;

/// <summary>
/// A generic locking selector.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RequirementsSelector : BoxContainer
{
    private readonly RadioOptions<int> _options;
    private readonly StripeBack _lockStripe;
    private List<ProtoId<GuideEntryPrototype>>? _guides;
    private List<ProtoId<JobAlternateTitlePrototype>>? _altTitles;

    public event Action<int>? OnSelected;
    public event Action<ProtoId<JobAlternateTitlePrototype>?>? OnSelectedTitle;
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    public int Selected => _options.SelectedId;

    public RequirementsSelector()
    {
        RobustXamlLoader.Load(this);
        _options = new RadioOptions<int>(RadioOptionsLayout.Horizontal)
        {
            FirstButtonStyle = StyleClass.ButtonOpenRight,
            ButtonStyle = StyleClass.ButtonOpenBoth,
            LastButtonStyle = StyleClass.ButtonOpenLeft,
            HorizontalExpand = true,
        };
        //Override default radio option button width
        _options.GenerateItem = GenerateButton;

        _options.OnItemSelected += args =>
        {
            _options.Select(args.Id);
            OnSelected?.Invoke(args.Id);
        };

        var requirementsLabel = new Label()
        {
            Text = Loc.GetString("role-timer-locked"),
            Visible = true,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = {StyleClass.LabelSubText},
        };

        _lockStripe = new StripeBack()
        {
            Visible = false,
            HorizontalExpand = true,
            HasMargins = false,
            MouseFilter = MouseFilterMode.Stop,
            Children =
            {
                requirementsLabel
            }
        };

        Help.OnPressed += _ =>
        {
            if (_guides != null)
                OnOpenGuidebook?.Invoke(_guides);
        };
    }

    /// <summary>
    /// Actually adds the controls.
    /// </summary>
    public void Setup(
        (string, int)[] items,
        string title,
        int titleSize,
        string? description,
        TextureRect? icon = null,
        List<ProtoId<GuideEntryPrototype>>? guides = null,
        List<(ProtoId<JobAlternateTitlePrototype> Id, bool Locked)>? altTitles = null,
        ProtoId<JobAlternateTitlePrototype>? defaultAltTitle = null,
        IPrototypeManager? protoMan = null)
    {
        foreach (var (text, value) in items)
        {
            _options.AddItem(Loc.GetString(text), value);
        }

        Help.Visible = guides != null;
        _guides = guides;

        // FIXED WIDTH LOGIC
        // We use the 'titleSize' passed from HumanoidProfileEditor (which is 280)
        // We lock both Min and Max to prevent any shrinking or growing.
        var fixedWidth = (float) titleSize;
        TitleContent.MinWidth = fixedWidth;
        TitleContent.MaxWidth = fixedWidth;

        if (altTitles != null && altTitles.Count > 0 && protoMan != null)
        {
            _altTitles = altTitles.Select(x => x.Id).ToList();

            var titleOptions = new OptionButton
            {
                ToolTip = description,
                // These three lines ensure the blue box fills the 280px exactly
                HorizontalExpand = true,
                MinWidth = fixedWidth,
                HorizontalAlignment = HAlignment.Stretch
            };

            titleOptions.AddItem(title);

            int idx = 1;
            foreach (var (id, locked) in altTitles)
            {
                var altTitle = protoMan.Index(id);
                var name = altTitle.LocalizedName;

                titleOptions.AddItem(name);

                if (locked)
                {
                    titleOptions.SetItemDisabled(idx, true);
                }
                idx++;
            }

            TitleContent.AddChild(titleOptions);

            if (defaultAltTitle != null)
            {
                var index = _altTitles.FindIndex(x => x == defaultAltTitle);

                if (index >= 0)
                {
                    var isLocked = altTitles[index].Locked;
                    if (isLocked)
                    {
                        titleOptions.SelectId(0);
                        OnSelectedTitle?.Invoke(null);
                    }
                    else
                    {
                        titleOptions.SelectId(index + 1);
                    }
                }
                else
                {
                    titleOptions.SelectId(0);
                }
            }
            else
            {
                titleOptions.SelectId(0);
            }

            titleOptions.OnItemSelected += args =>
            {
                titleOptions.SelectId(args.Id);
                if (args.Id == 0)
                    OnSelectedTitle?.Invoke(null);
                else
                    OnSelectedTitle?.Invoke(_altTitles[args.Id - 1]);
            };
        }
        else
        {
            var titleLabel = new Label
            {
                ToolTip = description,
                Text = title,
                // Ensure plain text titles (like "Mime") also occupy the same 280px
                HorizontalExpand = true,
                MinWidth = fixedWidth,
                HorizontalAlignment = HAlignment.Left
            };
            TitleContent.AddChild(titleLabel);
        }

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }

        OptionsContainer.AddChild(_options);
        OptionsContainer.AddChild(_lockStripe);
    }

    public void LockRequirements(FormattedMessage requirements)
    {
        var tooltip = new Tooltip();
        tooltip.SetMessage(requirements);
        _lockStripe.TooltipSupplier = _ => tooltip;
        _lockStripe.Visible = true;
        _options.Visible = false;
    }

    public void UnlockRequirements()
    {
        _lockStripe.Visible = false;
        _options.Visible = true;
    }

    private Button GenerateButton(string text, int value)
    {
        return new Button
        {
            Text = text,
            MinWidth = 60,
            HorizontalExpand = false,
        };
    }

    public void Select(int id)
    {
        _options.Select(id);
    }
}
