# SPDX-FileCopyrightText: 2024 PJBot <pieterjan.briers+bot@gmail.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 username <113782077+whateverusername0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: antag
  id: Heretic
  name: roles-antag-heretic-name
  antagonist: true
  setPreference: true
  objective: roles-antag-heretic-description
  guides: [ Heretics ]

- type: startingGear
  id: HereticGear
  storage:
    back:
    - CodexCicatrix
    - OrganHumanHeart