# SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Plykiya <58439124+Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: ghostRole
  id: SyndicateKobold
  name: ghost-role-information-syndicate-kobold-reinforcement-name
  description: ghost-role-information-syndicate-kobold-reinforcement-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobKoboldSyndicateAgent

- type: ghostRole
  id: SyndicateKoboldNukeops
  name: ghost-role-information-syndicate-kobold-reinforcement-name
  description: ghost-role-information-syndicate-kobold-reinforcement-description
  rules: ghost-role-information-nukeop-reinforcement-rules
  entityPrototype: MobKoboldSyndicateAgentNukeops

- type: ghostRole
  id: SyndicateMonkey
  name: ghost-role-information-syndicate-monkey-reinforcement-name
  description: ghost-role-information-syndicate-monkey-reinforcement-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobMonkeySyndicateAgent

- type: ghostRole
  id: SyndicateMonkeyNukeops
  name: ghost-role-information-syndicate-monkey-reinforcement-name
  description: ghost-role-information-syndicate-monkey-reinforcement-description
  rules: ghost-role-information-nukeop-reinforcement-rules
  entityPrototype: MobMonkeySyndicateAgentNukeops

- type: ghostRole
  id: SyndicateAgentMedic
  name: ghost-role-information-syndicate-reinforcement-medic-name
  description: ghost-role-information-syndicate-reinforcement-medic-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentMedic
  iconPrototype: MedkitCombat

- type: ghostRole
  id: SyndicateAgentSpy
  name: ghost-role-information-syndicate-reinforcement-spy-name
  description: ghost-role-information-syndicate-reinforcement-spy-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentSpy
  iconPrototype: ClothingMaskGasVoiceChameleon

- type: ghostRole
  id: SyndicateAgentThief
  name: ghost-role-information-syndicate-reinforcement-thief-name
  description: ghost-role-information-syndicate-reinforcement-thief-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentThief
  iconPrototype: SyndicateJawsOfLife
