name: No submodule update checker

on:
  pull_request:
    paths:
      - 'RobustToolbox'

jobs:
  this_aint_right:
    name: Submodule update in pr found
    if: github.actor != 'sleepyyapril' && github.actor != 'taydeo'
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
